// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Contact struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CustomerID           uint64   `protobuf:"varint,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_b3c6bf2926beef90, []int{0}
}
func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (dst *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(dst, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Contact) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ContactList struct {
	List                 []*Contact `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64     `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ContactList) Reset()         { *m = ContactList{} }
func (m *ContactList) String() string { return proto.CompactTextString(m) }
func (*ContactList) ProtoMessage()    {}
func (*ContactList) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_b3c6bf2926beef90, []int{1}
}
func (m *ContactList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactList.Unmarshal(m, b)
}
func (m *ContactList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactList.Marshal(b, m, deterministic)
}
func (dst *ContactList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactList.Merge(dst, src)
}
func (m *ContactList) XXX_Size() int {
	return xxx_messageInfo_ContactList.Size(m)
}
func (m *ContactList) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactList.DiscardUnknown(m)
}

var xxx_messageInfo_ContactList proto.InternalMessageInfo

func (m *ContactList) GetList() []*Contact {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ContactList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetContactsRequest struct {
	CustomerID           uint64   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactsRequest) Reset()         { *m = GetContactsRequest{} }
func (m *GetContactsRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactsRequest) ProtoMessage()    {}
func (*GetContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_b3c6bf2926beef90, []int{2}
}
func (m *GetContactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactsRequest.Unmarshal(m, b)
}
func (m *GetContactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactsRequest.Marshal(b, m, deterministic)
}
func (dst *GetContactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactsRequest.Merge(dst, src)
}
func (m *GetContactsRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactsRequest.Size(m)
}
func (m *GetContactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactsRequest proto.InternalMessageInfo

func (m *GetContactsRequest) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type GetContactRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactRequest) Reset()         { *m = GetContactRequest{} }
func (m *GetContactRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactRequest) ProtoMessage()    {}
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_b3c6bf2926beef90, []int{3}
}
func (m *GetContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactRequest.Unmarshal(m, b)
}
func (m *GetContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactRequest.Marshal(b, m, deterministic)
}
func (dst *GetContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactRequest.Merge(dst, src)
}
func (m *GetContactRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactRequest.Size(m)
}
func (m *GetContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactRequest proto.InternalMessageInfo

func (m *GetContactRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*Contact)(nil), "protos.Contact")
	proto.RegisterType((*ContactList)(nil), "protos.ContactList")
	proto.RegisterType((*GetContactsRequest)(nil), "protos.GetContactsRequest")
	proto.RegisterType((*GetContactRequest)(nil), "protos.GetContactRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactServiceClient is the client API for ContactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactServiceClient interface {
	Get(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*Contact, error)
	GetList(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*ContactList, error)
	Add(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Empty, error)
	Update(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Empty, error)
	Delete(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Empty, error)
}

type contactServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactServiceClient(cc *grpc.ClientConn) ContactServiceClient {
	return &contactServiceClient{cc}
}

func (c *contactServiceClient) Get(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*Contact, error) {
	out := new(Contact)
	err := c.cc.Invoke(ctx, "/protos.ContactService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) GetList(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*ContactList, error) {
	out := new(ContactList)
	err := c.cc.Invoke(ctx, "/protos.ContactService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) Add(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.ContactService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) Update(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.ContactService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) Delete(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.ContactService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServiceServer is the server API for ContactService service.
type ContactServiceServer interface {
	Get(context.Context, *GetContactRequest) (*Contact, error)
	GetList(context.Context, *GetContactsRequest) (*ContactList, error)
	Add(context.Context, *Contact) (*Empty, error)
	Update(context.Context, *Contact) (*Empty, error)
	Delete(context.Context, *Contact) (*Empty, error)
}

func RegisterContactServiceServer(s *grpc.Server, srv ContactServiceServer) {
	s.RegisterService(&_ContactService_serviceDesc, srv)
}

func _ContactService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ContactService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).Get(ctx, req.(*GetContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ContactService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).GetList(ctx, req.(*GetContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ContactService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).Add(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ContactService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).Update(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ContactService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).Delete(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ContactService",
	HandlerType: (*ContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ContactService_Get_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _ContactService_GetList_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _ContactService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ContactService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ContactService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contact",
}

func init() { proto.RegisterFile("contact", fileDescriptor_contact_b3c6bf2926beef90) }

var fileDescriptor_contact_b3c6bf2926beef90 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xc9, 0xda, 0x6d, 0xf8, 0x86, 0x13, 0x9f, 0x1e, 0x62, 0x0f, 0x32, 0x3a, 0x84, 0x9e,
	0x06, 0x4e, 0x4f, 0xde, 0x64, 0x1d, 0x73, 0x20, 0x22, 0x15, 0xff, 0x80, 0xda, 0x3e, 0xb0, 0xb0,
	0x34, 0xb5, 0x4d, 0x85, 0xfd, 0xeb, 0x9e, 0xa4, 0x49, 0x8a, 0x92, 0x1d, 0xf4, 0x94, 0xbc, 0xef,
	0x7d, 0xdf, 0xcb, 0x2f, 0x21, 0x30, 0xce, 0x64, 0xa9, 0xd2, 0x4c, 0xe1, 0xa8, 0xaa, 0xa5, 0x92,
	0x4d, 0x30, 0xca, 0xa4, 0x10, 0xb2, 0x0c, 0xf7, 0x30, 0x5e, 0xd9, 0xd6, 0x14, 0x06, 0xdb, 0x98,
	0xb3, 0x19, 0x8b, 0xfc, 0x64, 0xb0, 0x8d, 0xf1, 0x12, 0x60, 0xd5, 0x36, 0x4a, 0x0a, 0xaa, 0xb7,
	0x31, 0x1f, 0x68, 0xfd, 0x97, 0x82, 0x08, 0xfe, 0x53, 0x2a, 0x88, 0x7b, 0x33, 0x16, 0x1d, 0x25,
	0x7a, 0x8f, 0xe7, 0x30, 0x7c, 0x7e, 0x97, 0x25, 0x71, 0x5f, 0x8b, 0xa6, 0xe8, 0xd4, 0xb5, 0x48,
	0x8b, 0x1d, 0x1f, 0x1a, 0x55, 0x17, 0xe1, 0x03, 0x4c, 0xec, 0xd1, 0x8f, 0x45, 0xa3, 0x70, 0x0e,
	0x7e, 0xb7, 0x72, 0x36, 0xf3, 0xa2, 0xc9, 0xf2, 0x64, 0x61, 0x40, 0x17, 0xd6, 0x92, 0xe8, 0x66,
	0x37, 0x69, 0x25, 0xdb, 0x52, 0x59, 0x1c, 0x53, 0x84, 0xb7, 0x80, 0x1b, 0x52, 0xd6, 0xd9, 0x24,
	0xf4, 0xd1, 0x52, 0xa3, 0x1c, 0x7e, 0xe6, 0xf2, 0x87, 0x73, 0x38, 0xfd, 0x49, 0xf5, 0x21, 0xe7,
	0x11, 0x96, 0x5f, 0x0c, 0xa6, 0xd6, 0xf2, 0x42, 0xf5, 0x67, 0x91, 0x11, 0x5e, 0x83, 0xb7, 0x21,
	0x85, 0x17, 0x3d, 0xe1, 0xc1, 0x90, 0xc0, 0x85, 0xc7, 0x3b, 0x18, 0x6f, 0xc8, 0x5c, 0x33, 0x38,
	0x8c, 0xf5, 0xc4, 0xc1, 0x99, 0x93, 0xd3, 0x81, 0x2b, 0xf0, 0xee, 0xf3, 0x1c, 0xdd, 0x99, 0xc1,
	0x71, 0x2f, 0xac, 0x45, 0xa5, 0xf6, 0x18, 0xc1, 0xe8, 0xb5, 0xca, 0x53, 0x45, 0xff, 0x71, 0xc6,
	0xb4, 0xa3, 0xbf, 0x9d, 0x6f, 0xe6, 0xb3, 0xdc, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x06,
	0xf9, 0xd2, 0x3e, 0x02, 0x00, 0x00,
}
