// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_model

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceModel struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	ManufacturerID       uint64   `protobuf:"varint,10,opt,name=ManufacturerID,proto3" json:"ManufacturerID,omitempty"`
	DeviceTypeID         uint64   `protobuf:"varint,11,opt,name=DeviceTypeID,proto3" json:"DeviceTypeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceModel) Reset()         { *m = DeviceModel{} }
func (m *DeviceModel) String() string { return proto.CompactTextString(m) }
func (*DeviceModel) ProtoMessage()    {}
func (*DeviceModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_model_0fb2e76fe2c9d383, []int{0}
}
func (m *DeviceModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceModel.Unmarshal(m, b)
}
func (m *DeviceModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceModel.Marshal(b, m, deterministic)
}
func (dst *DeviceModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceModel.Merge(dst, src)
}
func (m *DeviceModel) XXX_Size() int {
	return xxx_messageInfo_DeviceModel.Size(m)
}
func (m *DeviceModel) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceModel.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceModel proto.InternalMessageInfo

func (m *DeviceModel) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DeviceModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DeviceModel) GetManufacturerID() uint64 {
	if m != nil {
		return m.ManufacturerID
	}
	return 0
}

func (m *DeviceModel) GetDeviceTypeID() uint64 {
	if m != nil {
		return m.DeviceTypeID
	}
	return 0
}

type DeviceModelList struct {
	List                 []*DeviceModel `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64         `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeviceModelList) Reset()         { *m = DeviceModelList{} }
func (m *DeviceModelList) String() string { return proto.CompactTextString(m) }
func (*DeviceModelList) ProtoMessage()    {}
func (*DeviceModelList) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_model_0fb2e76fe2c9d383, []int{1}
}
func (m *DeviceModelList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceModelList.Unmarshal(m, b)
}
func (m *DeviceModelList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceModelList.Marshal(b, m, deterministic)
}
func (dst *DeviceModelList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceModelList.Merge(dst, src)
}
func (m *DeviceModelList) XXX_Size() int {
	return xxx_messageInfo_DeviceModelList.Size(m)
}
func (m *DeviceModelList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceModelList.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceModelList proto.InternalMessageInfo

func (m *DeviceModelList) GetList() []*DeviceModel {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *DeviceModelList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetDeviceModelsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceModelsRequest) Reset()         { *m = GetDeviceModelsRequest{} }
func (m *GetDeviceModelsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceModelsRequest) ProtoMessage()    {}
func (*GetDeviceModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_model_0fb2e76fe2c9d383, []int{2}
}
func (m *GetDeviceModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceModelsRequest.Unmarshal(m, b)
}
func (m *GetDeviceModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceModelsRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeviceModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceModelsRequest.Merge(dst, src)
}
func (m *GetDeviceModelsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceModelsRequest.Size(m)
}
func (m *GetDeviceModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceModelsRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DeviceModel)(nil), "protos.DeviceModel")
	proto.RegisterType((*DeviceModelList)(nil), "protos.DeviceModelList")
	proto.RegisterType((*GetDeviceModelsRequest)(nil), "protos.GetDeviceModelsRequest")
}

func init() { proto.RegisterFile("device_model", fileDescriptor_device_model_0fb2e76fe2c9d383) }

var fileDescriptor_device_model_0fb2e76fe2c9d383 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x49, 0xa7, 0x0a, 0xde, 0x0e, 0x23, 0x5c, 0x45, 0xb2, 0x2c, 0x59, 0x68, 0x57, 0xb3,
	0xd0, 0x47, 0x30, 0x20, 0x01, 0x47, 0x24, 0xb8, 0x97, 0xda, 0xb9, 0x42, 0xc0, 0x69, 0x6a, 0x7e,
	0x04, 0x9f, 0xc6, 0x57, 0x95, 0xb9, 0xd9, 0x44, 0x57, 0x49, 0xbe, 0xf3, 0x25, 0x39, 0x09, 0xac,
	0xf7, 0xf4, 0xe5, 0x26, 0x7a, 0x3d, 0xf8, 0x3d, 0x7d, 0xe0, 0xe9, 0x12, 0x7c, 0xf2, 0x51, 0xfd,
	0x08, 0xe8, 0x34, 0x07, 0x3b, 0xe6, 0x1b, 0x68, 0x8c, 0x96, 0xa2, 0x17, 0x43, 0x6b, 0x1b, 0xa3,
	0x11, 0xa1, 0x7d, 0x1a, 0x0f, 0x24, 0x9b, 0x5e, 0x0c, 0x67, 0x96, 0xe7, 0xd8, 0x1f, 0xb7, 0xc4,
	0x29, 0xb8, 0x25, 0x39, 0x3f, 0xcb, 0x15, 0x47, 0x35, 0xc2, 0x6b, 0xd8, 0xec, 0xc6, 0x39, 0xbf,
	0x8f, 0x53, 0xca, 0x81, 0x82, 0xd1, 0x12, 0xf8, 0xc4, 0x7f, 0x14, 0x15, 0xac, 0xcb, 0xe5, 0x2f,
	0xdf, 0x0b, 0x19, 0x2d, 0x3b, 0xb6, 0xfe, 0x30, 0xf5, 0x0c, 0xe7, 0x55, 0xc1, 0x47, 0x17, 0x13,
	0xde, 0x40, 0x7b, 0x1c, 0xa5, 0xe8, 0x57, 0x43, 0x77, 0x7b, 0xb1, 0x2d, 0x6f, 0xd9, 0x56, 0x9a,
	0x65, 0x01, 0x2f, 0xe1, 0xe4, 0xde, 0xe7, 0x39, 0x71, 0xfd, 0xd6, 0x96, 0x85, 0x92, 0x70, 0xf5,
	0x40, 0xa9, 0xb2, 0xa3, 0xa5, 0xcf, 0x4c, 0x31, 0xbd, 0x95, 0x5f, 0xb9, 0xfb, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0xaf, 0xf1, 0xe0, 0x2c, 0x01, 0x00, 0x00,
}
