// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_management

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetDevicesRequestForCustomer struct {
	Pagination           *Pagination `protobuf:"bytes,1,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	CustomerID           uint64      `protobuf:"varint,10,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	DeviceTypeID         uint64      `protobuf:"varint,11,opt,name=DeviceTypeID,proto3" json:"DeviceTypeID,omitempty"`
	GroupID              uint64      `protobuf:"varint,12,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	DeviceModelID        uint64      `protobuf:"varint,13,opt,name=DeviceModelID,proto3" json:"DeviceModelID,omitempty"`
	SerialNumber         string      `protobuf:"bytes,14,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	Group                string      `protobuf:"bytes,20,opt,name=Group,proto3" json:"Group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDevicesRequestForCustomer) Reset()         { *m = GetDevicesRequestForCustomer{} }
func (m *GetDevicesRequestForCustomer) String() string { return proto.CompactTextString(m) }
func (*GetDevicesRequestForCustomer) ProtoMessage()    {}
func (*GetDevicesRequestForCustomer) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_management_d03fa2d2ad486daf, []int{0}
}
func (m *GetDevicesRequestForCustomer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesRequestForCustomer.Unmarshal(m, b)
}
func (m *GetDevicesRequestForCustomer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesRequestForCustomer.Marshal(b, m, deterministic)
}
func (dst *GetDevicesRequestForCustomer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesRequestForCustomer.Merge(dst, src)
}
func (m *GetDevicesRequestForCustomer) XXX_Size() int {
	return xxx_messageInfo_GetDevicesRequestForCustomer.Size(m)
}
func (m *GetDevicesRequestForCustomer) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesRequestForCustomer.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesRequestForCustomer proto.InternalMessageInfo

func (m *GetDevicesRequestForCustomer) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetDevicesRequestForCustomer) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *GetDevicesRequestForCustomer) GetDeviceTypeID() uint64 {
	if m != nil {
		return m.DeviceTypeID
	}
	return 0
}

func (m *GetDevicesRequestForCustomer) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *GetDevicesRequestForCustomer) GetDeviceModelID() uint64 {
	if m != nil {
		return m.DeviceModelID
	}
	return 0
}

func (m *GetDevicesRequestForCustomer) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *GetDevicesRequestForCustomer) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type DeviceWithAlarmThreshold struct {
	ID                   uint64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Position             string    `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position,omitempty"`
	SerialNumber         string    `protobuf:"bytes,4,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	GroupID              uint64    `protobuf:"varint,5,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Group                string    `protobuf:"bytes,6,opt,name=Group,proto3" json:"Group,omitempty"`
	DeviceModelID        uint64    `protobuf:"varint,7,opt,name=DeviceModelID,proto3" json:"DeviceModelID,omitempty"`
	DeviceModel          string    `protobuf:"bytes,8,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
	CreatedAt            string    `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	AlarmThresholds      []float64 `protobuf:"fixed64,20,rep,packed,name=AlarmThresholds,proto3" json:"AlarmThresholds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeviceWithAlarmThreshold) Reset()         { *m = DeviceWithAlarmThreshold{} }
func (m *DeviceWithAlarmThreshold) String() string { return proto.CompactTextString(m) }
func (*DeviceWithAlarmThreshold) ProtoMessage()    {}
func (*DeviceWithAlarmThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_management_d03fa2d2ad486daf, []int{1}
}
func (m *DeviceWithAlarmThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceWithAlarmThreshold.Unmarshal(m, b)
}
func (m *DeviceWithAlarmThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceWithAlarmThreshold.Marshal(b, m, deterministic)
}
func (dst *DeviceWithAlarmThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceWithAlarmThreshold.Merge(dst, src)
}
func (m *DeviceWithAlarmThreshold) XXX_Size() int {
	return xxx_messageInfo_DeviceWithAlarmThreshold.Size(m)
}
func (m *DeviceWithAlarmThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceWithAlarmThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceWithAlarmThreshold proto.InternalMessageInfo

func (m *DeviceWithAlarmThreshold) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DeviceWithAlarmThreshold) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceWithAlarmThreshold) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *DeviceWithAlarmThreshold) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *DeviceWithAlarmThreshold) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *DeviceWithAlarmThreshold) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *DeviceWithAlarmThreshold) GetDeviceModelID() uint64 {
	if m != nil {
		return m.DeviceModelID
	}
	return 0
}

func (m *DeviceWithAlarmThreshold) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *DeviceWithAlarmThreshold) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *DeviceWithAlarmThreshold) GetAlarmThresholds() []float64 {
	if m != nil {
		return m.AlarmThresholds
	}
	return nil
}

type AlarmThresholdList struct {
	Count                uint64                      `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	List                 []*DeviceWithAlarmThreshold `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	CurrentPage          uint64                      `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64                      `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64                      `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AlarmThresholdList) Reset()         { *m = AlarmThresholdList{} }
func (m *AlarmThresholdList) String() string { return proto.CompactTextString(m) }
func (*AlarmThresholdList) ProtoMessage()    {}
func (*AlarmThresholdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_management_d03fa2d2ad486daf, []int{2}
}
func (m *AlarmThresholdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmThresholdList.Unmarshal(m, b)
}
func (m *AlarmThresholdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmThresholdList.Marshal(b, m, deterministic)
}
func (dst *AlarmThresholdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmThresholdList.Merge(dst, src)
}
func (m *AlarmThresholdList) XXX_Size() int {
	return xxx_messageInfo_AlarmThresholdList.Size(m)
}
func (m *AlarmThresholdList) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmThresholdList.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmThresholdList proto.InternalMessageInfo

func (m *AlarmThresholdList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AlarmThresholdList) GetList() []*DeviceWithAlarmThreshold {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *AlarmThresholdList) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *AlarmThresholdList) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *AlarmThresholdList) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type SetAlarmThresholdRequest struct {
	DeviceSN             string    `protobuf:"bytes,1,opt,name=DeviceSN,proto3" json:"DeviceSN,omitempty"`
	CustomerID           uint64    `protobuf:"varint,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	DeviceTypeID         uint64    `protobuf:"varint,3,opt,name=DeviceTypeID,proto3" json:"DeviceTypeID,omitempty"`
	AlarmThresholds      []float64 `protobuf:"fixed64,4,rep,packed,name=AlarmThresholds,proto3" json:"AlarmThresholds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetAlarmThresholdRequest) Reset()         { *m = SetAlarmThresholdRequest{} }
func (m *SetAlarmThresholdRequest) String() string { return proto.CompactTextString(m) }
func (*SetAlarmThresholdRequest) ProtoMessage()    {}
func (*SetAlarmThresholdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_management_d03fa2d2ad486daf, []int{3}
}
func (m *SetAlarmThresholdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmThresholdRequest.Unmarshal(m, b)
}
func (m *SetAlarmThresholdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmThresholdRequest.Marshal(b, m, deterministic)
}
func (dst *SetAlarmThresholdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmThresholdRequest.Merge(dst, src)
}
func (m *SetAlarmThresholdRequest) XXX_Size() int {
	return xxx_messageInfo_SetAlarmThresholdRequest.Size(m)
}
func (m *SetAlarmThresholdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmThresholdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmThresholdRequest proto.InternalMessageInfo

func (m *SetAlarmThresholdRequest) GetDeviceSN() string {
	if m != nil {
		return m.DeviceSN
	}
	return ""
}

func (m *SetAlarmThresholdRequest) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *SetAlarmThresholdRequest) GetDeviceTypeID() uint64 {
	if m != nil {
		return m.DeviceTypeID
	}
	return 0
}

func (m *SetAlarmThresholdRequest) GetAlarmThresholds() []float64 {
	if m != nil {
		return m.AlarmThresholds
	}
	return nil
}

type DeviceGroupByType struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	Count                uint64   `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceGroupByType) Reset()         { *m = DeviceGroupByType{} }
func (m *DeviceGroupByType) String() string { return proto.CompactTextString(m) }
func (*DeviceGroupByType) ProtoMessage()    {}
func (*DeviceGroupByType) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_management_d03fa2d2ad486daf, []int{4}
}
func (m *DeviceGroupByType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceGroupByType.Unmarshal(m, b)
}
func (m *DeviceGroupByType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceGroupByType.Marshal(b, m, deterministic)
}
func (dst *DeviceGroupByType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceGroupByType.Merge(dst, src)
}
func (m *DeviceGroupByType) XXX_Size() int {
	return xxx_messageInfo_DeviceGroupByType.Size(m)
}
func (m *DeviceGroupByType) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceGroupByType.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceGroupByType proto.InternalMessageInfo

func (m *DeviceGroupByType) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DeviceGroupByType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceGroupByType) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeviceGroupByType) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetDeviceGroupsByTypeResponse struct {
	Count                uint64               `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	List                 []*DeviceGroupByType `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDeviceGroupsByTypeResponse) Reset()         { *m = GetDeviceGroupsByTypeResponse{} }
func (m *GetDeviceGroupsByTypeResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceGroupsByTypeResponse) ProtoMessage()    {}
func (*GetDeviceGroupsByTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_management_d03fa2d2ad486daf, []int{5}
}
func (m *GetDeviceGroupsByTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceGroupsByTypeResponse.Unmarshal(m, b)
}
func (m *GetDeviceGroupsByTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceGroupsByTypeResponse.Marshal(b, m, deterministic)
}
func (dst *GetDeviceGroupsByTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceGroupsByTypeResponse.Merge(dst, src)
}
func (m *GetDeviceGroupsByTypeResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceGroupsByTypeResponse.Size(m)
}
func (m *GetDeviceGroupsByTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceGroupsByTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceGroupsByTypeResponse proto.InternalMessageInfo

func (m *GetDeviceGroupsByTypeResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetDeviceGroupsByTypeResponse) GetList() []*DeviceGroupByType {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDevicesRequestForCustomer)(nil), "protos.GetDevicesRequestForCustomer")
	proto.RegisterType((*DeviceWithAlarmThreshold)(nil), "protos.DeviceWithAlarmThreshold")
	proto.RegisterType((*AlarmThresholdList)(nil), "protos.AlarmThresholdList")
	proto.RegisterType((*SetAlarmThresholdRequest)(nil), "protos.SetAlarmThresholdRequest")
	proto.RegisterType((*DeviceGroupByType)(nil), "protos.DeviceGroupByType")
	proto.RegisterType((*GetDeviceGroupsByTypeResponse)(nil), "protos.GetDeviceGroupsByTypeResponse")
}

func init() {
	proto.RegisterFile("device_management", fileDescriptor_device_management_d03fa2d2ad486daf)
}

var fileDescriptor_device_management_d03fa2d2ad486daf = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x1d, 0x37, 0x6d, 0x26, 0x6d, 0xa1, 0xab, 0x1c, 0x96, 0xaa, 0x20, 0xcb, 0xe2, 0xe0,
	0x0b, 0x3d, 0x04, 0x5e, 0xa0, 0xc4, 0xa2, 0xb2, 0x80, 0x28, 0xda, 0x44, 0xe2, 0x58, 0x6d, 0x9b,
	0x51, 0x62, 0x29, 0xf6, 0x86, 0xdd, 0x35, 0x52, 0x78, 0x0a, 0x1e, 0x82, 0xe7, 0xe8, 0xb3, 0x21,
	0xef, 0x26, 0xce, 0x3a, 0x75, 0x45, 0x6f, 0x9e, 0x6f, 0xc6, 0xf3, 0xf3, 0x7d, 0x9f, 0x0d, 0x17,
	0x73, 0xfc, 0x95, 0x3d, 0xe0, 0x5d, 0xce, 0x0b, 0xbe, 0xc0, 0x1c, 0x0b, 0x4d, 0xba, 0x6b, 0x29,
	0xb4, 0x50, 0x97, 0xdd, 0x07, 0x91, 0xe7, 0xa2, 0x88, 0xfe, 0xf8, 0x70, 0x75, 0x8b, 0x3a, 0x31,
	0x85, 0x8a, 0xe1, 0xcf, 0x12, 0x95, 0xfe, 0x22, 0xe4, 0xa8, 0x54, 0x5a, 0xe4, 0x28, 0xc9, 0x10,
	0x60, 0xc2, 0x17, 0x59, 0xc1, 0x75, 0x26, 0x0a, 0xea, 0x85, 0x5e, 0xdc, 0x1f, 0x92, 0x6b, 0xdb,
	0xe5, 0x7a, 0x9f, 0x61, 0x4e, 0x15, 0x79, 0x07, 0xb0, 0x7b, 0x3f, 0x4d, 0x28, 0x84, 0x5e, 0x1c,
	0x30, 0x07, 0x21, 0x11, 0x9c, 0xda, 0x81, 0xb3, 0xcd, 0x1a, 0xd3, 0x84, 0xf6, 0x4d, 0x45, 0x03,
	0x23, 0x14, 0x8e, 0x6f, 0xa5, 0x28, 0xd7, 0x69, 0x42, 0x4f, 0x4d, 0x7a, 0x17, 0x92, 0xf7, 0x70,
	0x66, 0x2b, 0xbf, 0x8b, 0x39, 0xae, 0xd2, 0x84, 0x9e, 0x99, 0x7c, 0x13, 0xac, 0x66, 0x4c, 0x51,
	0x66, 0x7c, 0x35, 0x2e, 0xf3, 0x7b, 0x94, 0xf4, 0x3c, 0xf4, 0xe2, 0x1e, 0x6b, 0x60, 0x64, 0x00,
	0x47, 0xa6, 0x29, 0x1d, 0x98, 0xa4, 0x0d, 0xa2, 0x47, 0x1f, 0xa8, 0xed, 0xf5, 0x23, 0xd3, 0xcb,
	0x9b, 0x15, 0x97, 0xf9, 0x6c, 0x29, 0x51, 0x2d, 0xc5, 0x6a, 0x4e, 0xce, 0xc1, 0x4f, 0x13, 0x43,
	0x43, 0xc0, 0xfc, 0x34, 0x21, 0x04, 0x82, 0x31, 0xcf, 0x91, 0xfa, 0xa6, 0x83, 0x79, 0x26, 0x97,
	0x70, 0x32, 0x11, 0x2a, 0x33, 0x84, 0x75, 0x0c, 0x5e, 0xc7, 0x4f, 0xd6, 0x0a, 0x5a, 0xd6, 0x72,
	0x4e, 0x3f, 0x6a, 0x9e, 0x5e, 0x2f, 0xdc, 0x75, 0x16, 0x7e, 0x4a, 0xc8, 0x71, 0x1b, 0x21, 0x21,
	0xf4, 0x1d, 0x80, 0x9e, 0x98, 0x0e, 0x2e, 0x44, 0xae, 0xa0, 0x37, 0x92, 0xc8, 0x35, 0xce, 0x6f,
	0xb4, 0xd1, 0xa4, 0xc7, 0xf6, 0x00, 0x89, 0xe1, 0x55, 0x93, 0x0b, 0x45, 0x07, 0x61, 0x27, 0xf6,
	0xd8, 0x21, 0x1c, 0x3d, 0x7a, 0x40, 0x9a, 0xd8, 0xb7, 0x4c, 0xe9, 0x6a, 0xf9, 0x91, 0x28, 0x0b,
	0xbd, 0x65, 0xcf, 0x06, 0xe4, 0x13, 0x04, 0x55, 0x96, 0xfa, 0x61, 0x27, 0xee, 0x0f, 0xc3, 0x9d,
	0xb3, 0x9e, 0x13, 0x80, 0x99, 0xea, 0xea, 0x98, 0x51, 0x29, 0x25, 0x16, 0x7a, 0xc2, 0x17, 0xb8,
	0xb5, 0x98, 0x0b, 0x19, 0x11, 0xf8, 0x02, 0xa7, 0xd9, 0x6f, 0xdc, 0xfa, 0xab, 0x8e, 0x2b, 0x7f,
	0xce, 0x84, 0xe6, 0x2b, 0xbb, 0x8e, 0xb5, 0x97, 0x83, 0x44, 0x7f, 0x3d, 0xa0, 0x53, 0xd4, 0x07,
	0x93, 0xed, 0xb7, 0x51, 0x35, 0xb6, 0xcb, 0x4d, 0xc7, 0xe6, 0x92, 0x1e, 0xab, 0xe3, 0x03, 0xe3,
	0xfb, 0xff, 0x35, 0x7e, 0xa7, 0xc5, 0xf8, 0x2d, 0x3c, 0x07, 0xed, 0x3c, 0xdf, 0xc1, 0x85, 0x7d,
	0xd3, 0xd8, 0xe0, 0xf3, 0xa6, 0x6a, 0xf0, 0x22, 0x83, 0xbe, 0x86, 0xce, 0x57, 0xdc, 0x6c, 0xbd,
	0x59, 0x3d, 0xee, 0xb5, 0x09, 0x1c, 0x6d, 0xa2, 0x39, 0xbc, 0xad, 0xff, 0x0d, 0x66, 0x86, 0xb2,
	0x43, 0x18, 0xaa, 0xb5, 0x28, 0x14, 0x3e, 0x23, 0xe9, 0x87, 0x86, 0xa4, 0x6f, 0x9a, 0x92, 0x3a,
	0xbb, 0x5a, 0x2d, 0xef, 0xed, 0x2f, 0xe9, 0xe3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xa8,
	0xe3, 0xd6, 0xae, 0x04, 0x00, 0x00,
}
