// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_type

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceType struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	IsSensor             bool     `protobuf:"varint,4,opt,name=IsSensor,proto3" json:"IsSensor,omitempty"`
	Properties           []string `protobuf:"bytes,10,rep,name=Properties,proto3" json:"Properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceType) Reset()         { *m = DeviceType{} }
func (m *DeviceType) String() string { return proto.CompactTextString(m) }
func (*DeviceType) ProtoMessage()    {}
func (*DeviceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_type_b72de75413fed10f, []int{0}
}
func (m *DeviceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceType.Unmarshal(m, b)
}
func (m *DeviceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceType.Marshal(b, m, deterministic)
}
func (dst *DeviceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceType.Merge(dst, src)
}
func (m *DeviceType) XXX_Size() int {
	return xxx_messageInfo_DeviceType.Size(m)
}
func (m *DeviceType) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceType.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceType proto.InternalMessageInfo

func (m *DeviceType) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DeviceType) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeviceType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceType) GetIsSensor() bool {
	if m != nil {
		return m.IsSensor
	}
	return false
}

func (m *DeviceType) GetProperties() []string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type DeviceTypeList struct {
	List                 []*DeviceType `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64        `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceTypeList) Reset()         { *m = DeviceTypeList{} }
func (m *DeviceTypeList) String() string { return proto.CompactTextString(m) }
func (*DeviceTypeList) ProtoMessage()    {}
func (*DeviceTypeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_type_b72de75413fed10f, []int{1}
}
func (m *DeviceTypeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceTypeList.Unmarshal(m, b)
}
func (m *DeviceTypeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceTypeList.Marshal(b, m, deterministic)
}
func (dst *DeviceTypeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceTypeList.Merge(dst, src)
}
func (m *DeviceTypeList) XXX_Size() int {
	return xxx_messageInfo_DeviceTypeList.Size(m)
}
func (m *DeviceTypeList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceTypeList.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceTypeList proto.InternalMessageInfo

func (m *DeviceTypeList) GetList() []*DeviceType {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *DeviceTypeList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetDeviceTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceTypesRequest) Reset()         { *m = GetDeviceTypesRequest{} }
func (m *GetDeviceTypesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceTypesRequest) ProtoMessage()    {}
func (*GetDeviceTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_type_b72de75413fed10f, []int{2}
}
func (m *GetDeviceTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceTypesRequest.Unmarshal(m, b)
}
func (m *GetDeviceTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceTypesRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeviceTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceTypesRequest.Merge(dst, src)
}
func (m *GetDeviceTypesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceTypesRequest.Size(m)
}
func (m *GetDeviceTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceTypesRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DeviceType)(nil), "protos.DeviceType")
	proto.RegisterType((*DeviceTypeList)(nil), "protos.DeviceTypeList")
	proto.RegisterType((*GetDeviceTypesRequest)(nil), "protos.GetDeviceTypesRequest")
}

func init() { proto.RegisterFile("device_type", fileDescriptor_device_type_b72de75413fed10f) }

var fileDescriptor_device_type_b72de75413fed10f = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x49, 0x13, 0xa5, 0x9d, 0x42, 0x91, 0x41, 0x31, 0x78, 0x90, 0xd0, 0x83, 0xe4, 0xd4,
	0x83, 0xfe, 0x04, 0x0b, 0x52, 0x94, 0x22, 0xd1, 0xbb, 0xb8, 0xbb, 0x73, 0xe8, 0x61, 0x9b, 0x6e,
	0x92, 0x2e, 0xf4, 0xb2, 0xbf, 0x7d, 0x69, 0x0a, 0xdb, 0x3d, 0xcd, 0x7b, 0xdf, 0x3c, 0x98, 0x37,
	0x90, 0xef, 0xe8, 0xd8, 0x6d, 0xe9, 0x2f, 0x4c, 0x03, 0xe1, 0xed, 0xe0, 0x6c, 0xb0, 0xbe, 0x3c,
	0x01, 0xd4, 0x11, 0xff, 0xce, 0xb4, 0x80, 0xa4, 0xa9, 0x25, 0x53, 0x4c, 0x0b, 0x93, 0x34, 0x35,
	0xde, 0x01, 0xff, 0xa4, 0x49, 0x26, 0x8a, 0xe9, 0xcc, 0xcc, 0x12, 0x11, 0x44, 0xfb, 0xbf, 0x27,
	0xc9, 0x23, 0x8a, 0x1a, 0x9f, 0x20, 0x6d, 0xfc, 0x0f, 0xf5, 0xde, 0x3a, 0x29, 0x14, 0xd3, 0xa9,
	0xb9, 0x78, 0x7c, 0x06, 0xf8, 0x76, 0x76, 0x20, 0x17, 0x3a, 0xf2, 0x12, 0x14, 0xd7, 0x99, 0xb9,
	0x22, 0x65, 0x0b, 0xc5, 0x7a, 0xff, 0xab, 0xf3, 0x01, 0x5f, 0x40, 0xcc, 0x53, 0x32, 0xc5, 0x75,
	0xfe, 0x8a, 0xd5, 0x52, 0xb4, 0x5a, 0x53, 0x26, 0xee, 0xf1, 0x1e, 0x6e, 0xde, 0xed, 0xd8, 0x87,
	0xd8, 0x4e, 0x98, 0xc5, 0x94, 0x8f, 0xf0, 0xf0, 0x41, 0x61, 0x0d, 0x7b, 0x43, 0x87, 0x91, 0x7c,
	0xd8, 0x2c, 0x0f, 0xbf, 0x9d, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xfc, 0x7a, 0x32, 0x06, 0x01,
	0x00, 0x00,
}
