// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geomagnetic

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ParkingPlace struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Used                 uint64   `protobuf:"varint,4,opt,name=Used,proto3" json:"Used,omitempty"`
	Unused               uint64   `protobuf:"varint,5,opt,name=Unused,proto3" json:"Unused,omitempty"`
	Longitude            float64  `protobuf:"fixed64,10,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,11,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParkingPlace) Reset()         { *m = ParkingPlace{} }
func (m *ParkingPlace) String() string { return proto.CompactTextString(m) }
func (*ParkingPlace) ProtoMessage()    {}
func (*ParkingPlace) Descriptor() ([]byte, []int) {
	return fileDescriptor_geomagnetic_e4235eb74cc0d1d8, []int{0}
}
func (m *ParkingPlace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParkingPlace.Unmarshal(m, b)
}
func (m *ParkingPlace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParkingPlace.Marshal(b, m, deterministic)
}
func (dst *ParkingPlace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParkingPlace.Merge(dst, src)
}
func (m *ParkingPlace) XXX_Size() int {
	return xxx_messageInfo_ParkingPlace.Size(m)
}
func (m *ParkingPlace) XXX_DiscardUnknown() {
	xxx_messageInfo_ParkingPlace.DiscardUnknown(m)
}

var xxx_messageInfo_ParkingPlace proto.InternalMessageInfo

func (m *ParkingPlace) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ParkingPlace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParkingPlace) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ParkingPlace) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *ParkingPlace) GetUnused() uint64 {
	if m != nil {
		return m.Unused
	}
	return 0
}

func (m *ParkingPlace) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *ParkingPlace) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type ParkingPlaceList struct {
	List                 []*ParkingPlace `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64          `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	CurrentPage          uint64          `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64          `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64          `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ParkingPlaceList) Reset()         { *m = ParkingPlaceList{} }
func (m *ParkingPlaceList) String() string { return proto.CompactTextString(m) }
func (*ParkingPlaceList) ProtoMessage()    {}
func (*ParkingPlaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_geomagnetic_e4235eb74cc0d1d8, []int{1}
}
func (m *ParkingPlaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParkingPlaceList.Unmarshal(m, b)
}
func (m *ParkingPlaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParkingPlaceList.Marshal(b, m, deterministic)
}
func (dst *ParkingPlaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParkingPlaceList.Merge(dst, src)
}
func (m *ParkingPlaceList) XXX_Size() int {
	return xxx_messageInfo_ParkingPlaceList.Size(m)
}
func (m *ParkingPlaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ParkingPlaceList.DiscardUnknown(m)
}

var xxx_messageInfo_ParkingPlaceList proto.InternalMessageInfo

func (m *ParkingPlaceList) GetList() []*ParkingPlace {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ParkingPlaceList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ParkingPlaceList) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ParkingPlaceList) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ParkingPlaceList) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type GetParkingPlacesRequest struct {
	Pagination           *Pagination `protobuf:"bytes,1,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	CustomerID           uint64      `protobuf:"varint,10,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetParkingPlacesRequest) Reset()         { *m = GetParkingPlacesRequest{} }
func (m *GetParkingPlacesRequest) String() string { return proto.CompactTextString(m) }
func (*GetParkingPlacesRequest) ProtoMessage()    {}
func (*GetParkingPlacesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_geomagnetic_e4235eb74cc0d1d8, []int{2}
}
func (m *GetParkingPlacesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParkingPlacesRequest.Unmarshal(m, b)
}
func (m *GetParkingPlacesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParkingPlacesRequest.Marshal(b, m, deterministic)
}
func (dst *GetParkingPlacesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParkingPlacesRequest.Merge(dst, src)
}
func (m *GetParkingPlacesRequest) XXX_Size() int {
	return xxx_messageInfo_GetParkingPlacesRequest.Size(m)
}
func (m *GetParkingPlacesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParkingPlacesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetParkingPlacesRequest proto.InternalMessageInfo

func (m *GetParkingPlacesRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetParkingPlacesRequest) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

// 与普通Device结构相比, GeomagneticDevice多了一个占用率字段
type GeomagneticDevice struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	SerialNumber         string   `protobuf:"bytes,3,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Position             string   `protobuf:"bytes,5,opt,name=Position,proto3" json:"Position,omitempty"`
	Group                string   `protobuf:"bytes,11,opt,name=Group,proto3" json:"Group,omitempty"`
	GroupID              uint64   `protobuf:"varint,12,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	DeviceType           string   `protobuf:"bytes,13,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	DeviceTypeID         uint64   `protobuf:"varint,14,opt,name=DeviceTypeID,proto3" json:"DeviceTypeID,omitempty"`
	DeviceModel          string   `protobuf:"bytes,15,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
	DeviceModelID        uint64   `protobuf:"varint,16,opt,name=DeviceModelID,proto3" json:"DeviceModelID,omitempty"`
	Customer             string   `protobuf:"bytes,17,opt,name=Customer,proto3" json:"Customer,omitempty"`
	CustomerID           uint64   `protobuf:"varint,18,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Latitude             float64  `protobuf:"fixed64,21,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,22,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	StatusCode           int32    `protobuf:"varint,23,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Status               string   `protobuf:"bytes,24,opt,name=Status,proto3" json:"Status,omitempty"`
	Used                 string   `protobuf:"bytes,30,opt,name=Used,proto3" json:"Used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeomagneticDevice) Reset()         { *m = GeomagneticDevice{} }
func (m *GeomagneticDevice) String() string { return proto.CompactTextString(m) }
func (*GeomagneticDevice) ProtoMessage()    {}
func (*GeomagneticDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_geomagnetic_e4235eb74cc0d1d8, []int{3}
}
func (m *GeomagneticDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeomagneticDevice.Unmarshal(m, b)
}
func (m *GeomagneticDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeomagneticDevice.Marshal(b, m, deterministic)
}
func (dst *GeomagneticDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeomagneticDevice.Merge(dst, src)
}
func (m *GeomagneticDevice) XXX_Size() int {
	return xxx_messageInfo_GeomagneticDevice.Size(m)
}
func (m *GeomagneticDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_GeomagneticDevice.DiscardUnknown(m)
}

var xxx_messageInfo_GeomagneticDevice proto.InternalMessageInfo

func (m *GeomagneticDevice) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GeomagneticDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GeomagneticDevice) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *GeomagneticDevice) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GeomagneticDevice) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *GeomagneticDevice) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GeomagneticDevice) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *GeomagneticDevice) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *GeomagneticDevice) GetDeviceTypeID() uint64 {
	if m != nil {
		return m.DeviceTypeID
	}
	return 0
}

func (m *GeomagneticDevice) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *GeomagneticDevice) GetDeviceModelID() uint64 {
	if m != nil {
		return m.DeviceModelID
	}
	return 0
}

func (m *GeomagneticDevice) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *GeomagneticDevice) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *GeomagneticDevice) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GeomagneticDevice) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *GeomagneticDevice) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GeomagneticDevice) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GeomagneticDevice) GetUsed() string {
	if m != nil {
		return m.Used
	}
	return ""
}

type GeomagneticDeviceList struct {
	List                 []*GeomagneticDevice `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64               `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	CurrentPage          uint64               `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64               `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64               `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GeomagneticDeviceList) Reset()         { *m = GeomagneticDeviceList{} }
func (m *GeomagneticDeviceList) String() string { return proto.CompactTextString(m) }
func (*GeomagneticDeviceList) ProtoMessage()    {}
func (*GeomagneticDeviceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_geomagnetic_e4235eb74cc0d1d8, []int{4}
}
func (m *GeomagneticDeviceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeomagneticDeviceList.Unmarshal(m, b)
}
func (m *GeomagneticDeviceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeomagneticDeviceList.Marshal(b, m, deterministic)
}
func (dst *GeomagneticDeviceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeomagneticDeviceList.Merge(dst, src)
}
func (m *GeomagneticDeviceList) XXX_Size() int {
	return xxx_messageInfo_GeomagneticDeviceList.Size(m)
}
func (m *GeomagneticDeviceList) XXX_DiscardUnknown() {
	xxx_messageInfo_GeomagneticDeviceList.DiscardUnknown(m)
}

var xxx_messageInfo_GeomagneticDeviceList proto.InternalMessageInfo

func (m *GeomagneticDeviceList) GetList() []*GeomagneticDevice {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GeomagneticDeviceList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GeomagneticDeviceList) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *GeomagneticDeviceList) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GeomagneticDeviceList) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ParkingPlace)(nil), "protos.ParkingPlace")
	proto.RegisterType((*ParkingPlaceList)(nil), "protos.ParkingPlaceList")
	proto.RegisterType((*GetParkingPlacesRequest)(nil), "protos.GetParkingPlacesRequest")
	proto.RegisterType((*GeomagneticDevice)(nil), "protos.GeomagneticDevice")
	proto.RegisterType((*GeomagneticDeviceList)(nil), "protos.GeomagneticDeviceList")
}

func init() { proto.RegisterFile("geomagnetic", fileDescriptor_geomagnetic_e4235eb74cc0d1d8) }

var fileDescriptor_geomagnetic_e4235eb74cc0d1d8 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x4d, 0x6e, 0xdb, 0x3c,
	0x10, 0x85, 0x1c, 0xd9, 0xdf, 0xe7, 0x91, 0x93, 0x26, 0x44, 0x7e, 0xd8, 0xa0, 0x30, 0x04, 0xa1,
	0x0b, 0x6d, 0x9a, 0x85, 0x7b, 0x82, 0xc2, 0x02, 0x0c, 0x01, 0x6e, 0x60, 0xd0, 0xc9, 0x01, 0x18,
	0x9b, 0x10, 0x88, 0x5a, 0xa2, 0x2b, 0x91, 0x05, 0xda, 0x8b, 0xf4, 0x1a, 0x5d, 0xf7, 0x74, 0x05,
	0x87, 0x96, 0x4c, 0x39, 0x9b, 0xee, 0xba, 0xd2, 0xbc, 0x37, 0x4f, 0xf2, 0x9b, 0x3f, 0x43, 0x54,
	0x08, 0x55, 0xf2, 0xa2, 0x12, 0x5a, 0x6e, 0xc8, 0x68, 0x5f, 0x2b, 0xad, 0x9a, 0xfb, 0xd1, 0x46,
	0x95, 0xa5, 0xaa, 0x92, 0x5f, 0x01, 0x4c, 0x56, 0xbc, 0xfe, 0x22, 0xab, 0x62, 0xb5, 0xe3, 0x1b,
	0x41, 0x2e, 0x60, 0x90, 0x67, 0x34, 0x88, 0x83, 0x34, 0x64, 0x83, 0x3c, 0x23, 0x04, 0xc2, 0x47,
	0x5e, 0x0a, 0x3a, 0x88, 0x83, 0x74, 0xcc, 0x30, 0x26, 0xb7, 0x30, 0xfa, 0x54, 0x2a, 0x53, 0x69,
	0x7a, 0x86, 0xba, 0x03, 0xb2, 0xda, 0xe7, 0x46, 0x6c, 0x69, 0x88, 0x2c, 0xc6, 0x56, 0xfb, 0x5c,
	0x19, 0xcb, 0x0e, 0x9d, 0xd6, 0x21, 0xf2, 0x0e, 0xc6, 0x4b, 0x55, 0x15, 0x52, 0x9b, 0xad, 0xa0,
	0x10, 0x07, 0x69, 0xc0, 0x8e, 0x04, 0xb9, 0x87, 0xff, 0x97, 0x5c, 0xbb, 0x64, 0x84, 0xc9, 0x0e,
	0x5b, 0xcb, 0x97, 0xbe, 0xe5, 0xa5, 0x6c, 0x34, 0x49, 0x21, 0xb4, 0x4f, 0x1a, 0xc4, 0x67, 0x69,
	0x34, 0xbb, 0x7e, 0x70, 0x65, 0x3e, 0xf8, 0x3a, 0x86, 0x0a, 0x72, 0x0d, 0xc3, 0x39, 0x7a, 0x1f,
	0xa0, 0x1f, 0x07, 0x48, 0x0c, 0xd1, 0xdc, 0xd4, 0xb5, 0xa8, 0xf4, 0x8a, 0x17, 0xce, 0x50, 0xc8,
	0x7c, 0xca, 0x5a, 0xb2, 0xcf, 0xb5, 0xfc, 0xe1, 0x2c, 0x85, 0xac, 0xc3, 0x64, 0x0a, 0xf0, 0xa4,
	0x34, 0xdf, 0xb9, 0x0f, 0x4f, 0x30, 0xeb, 0x31, 0x49, 0x09, 0x77, 0x0b, 0xa1, 0x7d, 0x33, 0x0d,
	0x13, 0x5f, 0x8d, 0x68, 0x34, 0x99, 0x01, 0xac, 0x78, 0x21, 0x2b, 0xae, 0xa5, 0xaa, 0xb0, 0xef,
	0xd1, 0x8c, 0x1c, 0xed, 0xb7, 0x19, 0xe6, 0xa9, 0xec, 0xcf, 0xcd, 0x4d, 0xa3, 0x55, 0x29, 0xea,
	0x3c, 0x3b, 0x78, 0xf5, 0x98, 0xe4, 0x67, 0x08, 0x57, 0x8b, 0xe3, 0xd0, 0x33, 0xf1, 0x4d, 0xfe,
	0xe5, 0x64, 0x13, 0x98, 0xac, 0x45, 0x2d, 0xf9, 0xee, 0xd1, 0x94, 0x2f, 0xa2, 0xc6, 0xf9, 0x8e,
	0x59, 0x8f, 0xb3, 0xad, 0xca, 0x44, 0xb3, 0xa9, 0xe5, 0x1e, 0x2d, 0x87, 0x28, 0xf1, 0x29, 0x6c,
	0x95, 0x6a, 0x24, 0xa6, 0x87, 0x98, 0xee, 0xb0, 0x6d, 0xff, 0xa2, 0x56, 0x66, 0x8f, 0x3d, 0x1c,
	0x33, 0x07, 0x08, 0x85, 0xff, 0x30, 0xc8, 0xb3, 0x43, 0xf7, 0x5a, 0x68, 0x6b, 0x75, 0xfe, 0x9f,
	0xbe, 0xef, 0x05, 0x3d, 0xc7, 0x97, 0x3c, 0xc6, 0x3a, 0x3e, 0xa2, 0x3c, 0xa3, 0x17, 0xf8, 0x7a,
	0x8f, 0x73, 0x8e, 0x2d, 0xfe, 0xac, 0xb6, 0x62, 0x47, 0xdf, 0xb4, 0x8e, 0x3b, 0x8a, 0xbc, 0x87,
	0x73, 0x0f, 0xe6, 0x19, 0xbd, 0xc4, 0xcf, 0xf4, 0x49, 0x5b, 0x57, 0xdb, 0x65, 0x7a, 0xe5, 0xea,
	0x6a, 0xf1, 0xc9, 0x4c, 0xc8, 0xe9, 0x4c, 0x7a, 0x1b, 0x7d, 0xd3, 0xdf, 0xe8, 0xfe, 0x2d, 0xdc,
	0x9e, 0xde, 0xc2, 0x14, 0x60, 0xad, 0xb9, 0x36, 0xcd, 0x5c, 0x6d, 0x05, 0xbd, 0x8b, 0x83, 0x74,
	0xc8, 0x3c, 0xc6, 0x5e, 0x98, 0x43, 0x94, 0xa2, 0xa7, 0x03, 0xea, 0xae, 0x71, 0xea, 0xe6, 0x6b,
	0xe3, 0xe4, 0x77, 0x00, 0x37, 0xaf, 0x36, 0x03, 0xcf, 0xe2, 0x43, 0xef, 0x80, 0xde, 0xb6, 0x1b,
	0xf8, 0x4a, 0xfc, 0xef, 0xae, 0xe8, 0xc5, 0xfd, 0x77, 0x7d, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xcf, 0x3e, 0x88, 0xe5, 0xd1, 0x04, 0x00, 0x00,
}
