// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Group struct {
	ID            uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DeviceTypeID  uint64 `protobuf:"varint,3,opt,name=DeviceTypeID,proto3" json:"DeviceTypeID,omitempty"`
	CustomerID    uint64 `protobuf:"varint,4,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Status        uint32 `protobuf:"varint,10,opt,name=Status,proto3" json:"Status,omitempty"`
	DeviceType    string `protobuf:"bytes,11,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	CustomerTitle string `protobuf:"bytes,12,opt,name=CustomerTitle,proto3" json:"CustomerTitle,omitempty"`
	// 这是响应体中才有的字段, 之后应该分开定义
	DeviceCount          uint64   `protobuf:"varint,20,opt,name=DeviceCount,proto3" json:"DeviceCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_99a5eaaf0d19783f, []int{0}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDeviceTypeID() uint64 {
	if m != nil {
		return m.DeviceTypeID
	}
	return 0
}

func (m *Group) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Group) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Group) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *Group) GetCustomerTitle() string {
	if m != nil {
		return m.CustomerTitle
	}
	return ""
}

func (m *Group) GetDeviceCount() uint64 {
	if m != nil {
		return m.DeviceCount
	}
	return 0
}

type GroupList struct {
	List                 []*Group `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupList) Reset()         { *m = GroupList{} }
func (m *GroupList) String() string { return proto.CompactTextString(m) }
func (*GroupList) ProtoMessage()    {}
func (*GroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_99a5eaaf0d19783f, []int{1}
}
func (m *GroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupList.Unmarshal(m, b)
}
func (m *GroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupList.Marshal(b, m, deterministic)
}
func (dst *GroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupList.Merge(dst, src)
}
func (m *GroupList) XXX_Size() int {
	return xxx_messageInfo_GroupList.Size(m)
}
func (m *GroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupList.DiscardUnknown(m)
}

var xxx_messageInfo_GroupList proto.InternalMessageInfo

func (m *GroupList) GetList() []*Group {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GroupList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 不分页
type GetGroupsRequest struct {
	CustomerID           uint64   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupsRequest) Reset()         { *m = GetGroupsRequest{} }
func (m *GetGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupsRequest) ProtoMessage()    {}
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_99a5eaaf0d19783f, []int{2}
}
func (m *GetGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupsRequest.Unmarshal(m, b)
}
func (m *GetGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupsRequest.Marshal(b, m, deterministic)
}
func (dst *GetGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupsRequest.Merge(dst, src)
}
func (m *GetGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupsRequest.Size(m)
}
func (m *GetGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupsRequest proto.InternalMessageInfo

func (m *GetGroupsRequest) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type DeleteGroupRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_99a5eaaf0d19783f, []int{3}
}
func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(dst, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*Group)(nil), "protos.Group")
	proto.RegisterType((*GroupList)(nil), "protos.GroupList")
	proto.RegisterType((*GetGroupsRequest)(nil), "protos.GetGroupsRequest")
	proto.RegisterType((*DeleteGroupRequest)(nil), "protos.DeleteGroupRequest")
}

func init() { proto.RegisterFile("group", fileDescriptor_group_99a5eaaf0d19783f) }

var fileDescriptor_group_99a5eaaf0d19783f = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x6a, 0xc3, 0x30,
	0x0c, 0x86, 0x71, 0x9a, 0x16, 0xaa, 0x34, 0x63, 0x88, 0x32, 0x7c, 0x1a, 0x99, 0xe9, 0x21, 0xa7,
	0x1e, 0xba, 0x47, 0xa8, 0xa1, 0x04, 0xc6, 0x0e, 0x5e, 0x5f, 0xa0, 0x1b, 0x62, 0x04, 0xda, 0x39,
	0x8b, 0xe5, 0xc1, 0x9e, 0x7a, 0xaf, 0x30, 0x2a, 0x77, 0x2c, 0xcd, 0xc9, 0xd6, 0xe7, 0x5f, 0xbf,
	0xf8, 0x65, 0x98, 0xbe, 0xf7, 0x3e, 0x76, 0x38, 0xeb, 0x7a, 0xcf, 0x3e, 0x98, 0x1f, 0x05, 0xd3,
	0x9d, 0x90, 0x1b, 0xc8, 0x1a, 0xab, 0x55, 0xa5, 0xea, 0xdc, 0x65, 0x8d, 0x45, 0x84, 0xfc, 0xf9,
	0x70, 0x22, 0x9d, 0x55, 0xaa, 0x9e, 0x3b, 0xb9, 0xa3, 0x81, 0x85, 0xa5, 0xaf, 0xf6, 0x8d, 0xf6,
	0xdf, 0x1d, 0x35, 0x56, 0x4f, 0x44, 0x7d, 0xc5, 0xf0, 0x1e, 0x60, 0x1b, 0x03, 0xfb, 0x13, 0xf5,
	0x8d, 0xd5, 0xb9, 0x28, 0x06, 0x04, 0xef, 0x60, 0xf6, 0xc2, 0x07, 0x8e, 0x41, 0x43, 0xa5, 0xea,
	0xd2, 0x5d, 0xaa, 0x73, 0xdf, 0xbf, 0x8f, 0x2e, 0x64, 0xea, 0x80, 0xe0, 0x0a, 0xca, 0x3f, 0x97,
	0x7d, 0xcb, 0x47, 0xd2, 0x0b, 0x91, 0x5c, 0x43, 0xac, 0xa0, 0x48, 0x3d, 0x5b, 0x1f, 0x3f, 0x58,
	0x2f, 0x65, 0xfc, 0x10, 0x19, 0x0b, 0x73, 0x09, 0xfc, 0xd4, 0x06, 0xc6, 0x07, 0xc8, 0xcf, 0xa7,
	0x56, 0xd5, 0xa4, 0x2e, 0x36, 0xe5, 0x3a, 0x6d, 0x65, 0x2d, 0x02, 0x27, 0x4f, 0xb8, 0x84, 0x69,
	0xf2, 0xca, 0xc4, 0x2b, 0x15, 0x66, 0x03, 0xb7, 0x3b, 0x62, 0xd1, 0x05, 0x47, 0x9f, 0x91, 0x02,
	0x8f, 0x92, 0xab, 0x71, 0x72, 0xb3, 0x02, 0xb4, 0x74, 0x24, 0xa6, 0x64, 0x7f, 0xe9, 0x1a, 0xed,
	0xfd, 0x35, 0xfd, 0xcc, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x09, 0xa4, 0x8e, 0xa9,
	0x01, 0x00, 0x00,
}
