// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loraclient

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoraclientCustormer struct {
	OrgName              string   `protobuf:"bytes,1,opt,name=OrgName,proto3" json:"OrgName,omitempty"`
	OrgDisplayName       string   `protobuf:"bytes,2,opt,name=OrgDisplayName,proto3" json:"OrgDisplayName,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Passwd               string   `protobuf:"bytes,4,opt,name=Passwd,proto3" json:"Passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoraclientCustormer) Reset()         { *m = LoraclientCustormer{} }
func (m *LoraclientCustormer) String() string { return proto.CompactTextString(m) }
func (*LoraclientCustormer) ProtoMessage()    {}
func (*LoraclientCustormer) Descriptor() ([]byte, []int) {
	return fileDescriptor_loraclient_7b174a694fa68362, []int{0}
}
func (m *LoraclientCustormer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraclientCustormer.Unmarshal(m, b)
}
func (m *LoraclientCustormer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraclientCustormer.Marshal(b, m, deterministic)
}
func (dst *LoraclientCustormer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraclientCustormer.Merge(dst, src)
}
func (m *LoraclientCustormer) XXX_Size() int {
	return xxx_messageInfo_LoraclientCustormer.Size(m)
}
func (m *LoraclientCustormer) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraclientCustormer.DiscardUnknown(m)
}

var xxx_messageInfo_LoraclientCustormer proto.InternalMessageInfo

func (m *LoraclientCustormer) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *LoraclientCustormer) GetOrgDisplayName() string {
	if m != nil {
		return m.OrgDisplayName
	}
	return ""
}

func (m *LoraclientCustormer) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoraclientCustormer) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type LoraclientAddCustormerResponse struct {
	OrgID                int64    `protobuf:"varint,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoraclientAddCustormerResponse) Reset()         { *m = LoraclientAddCustormerResponse{} }
func (m *LoraclientAddCustormerResponse) String() string { return proto.CompactTextString(m) }
func (*LoraclientAddCustormerResponse) ProtoMessage()    {}
func (*LoraclientAddCustormerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_loraclient_7b174a694fa68362, []int{1}
}
func (m *LoraclientAddCustormerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraclientAddCustormerResponse.Unmarshal(m, b)
}
func (m *LoraclientAddCustormerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraclientAddCustormerResponse.Marshal(b, m, deterministic)
}
func (dst *LoraclientAddCustormerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraclientAddCustormerResponse.Merge(dst, src)
}
func (m *LoraclientAddCustormerResponse) XXX_Size() int {
	return xxx_messageInfo_LoraclientAddCustormerResponse.Size(m)
}
func (m *LoraclientAddCustormerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraclientAddCustormerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoraclientAddCustormerResponse proto.InternalMessageInfo

func (m *LoraclientAddCustormerResponse) GetOrgID() int64 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *LoraclientAddCustormerResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type LoraclientUpdateCustormerRequest struct {
	OrgID                int64    `protobuf:"varint,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	OrgName              string   `protobuf:"bytes,2,opt,name=OrgName,proto3" json:"OrgName,omitempty"`
	OrgDisplayName       string   `protobuf:"bytes,3,opt,name=OrgDisplayName,proto3" json:"OrgDisplayName,omitempty"`
	UserID               int64    `protobuf:"varint,11,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName             string   `protobuf:"bytes,12,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Passwd               string   `protobuf:"bytes,13,opt,name=Passwd,proto3" json:"Passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoraclientUpdateCustormerRequest) Reset()         { *m = LoraclientUpdateCustormerRequest{} }
func (m *LoraclientUpdateCustormerRequest) String() string { return proto.CompactTextString(m) }
func (*LoraclientUpdateCustormerRequest) ProtoMessage()    {}
func (*LoraclientUpdateCustormerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_loraclient_7b174a694fa68362, []int{2}
}
func (m *LoraclientUpdateCustormerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraclientUpdateCustormerRequest.Unmarshal(m, b)
}
func (m *LoraclientUpdateCustormerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraclientUpdateCustormerRequest.Marshal(b, m, deterministic)
}
func (dst *LoraclientUpdateCustormerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraclientUpdateCustormerRequest.Merge(dst, src)
}
func (m *LoraclientUpdateCustormerRequest) XXX_Size() int {
	return xxx_messageInfo_LoraclientUpdateCustormerRequest.Size(m)
}
func (m *LoraclientUpdateCustormerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraclientUpdateCustormerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoraclientUpdateCustormerRequest proto.InternalMessageInfo

func (m *LoraclientUpdateCustormerRequest) GetOrgID() int64 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *LoraclientUpdateCustormerRequest) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *LoraclientUpdateCustormerRequest) GetOrgDisplayName() string {
	if m != nil {
		return m.OrgDisplayName
	}
	return ""
}

func (m *LoraclientUpdateCustormerRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LoraclientUpdateCustormerRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoraclientUpdateCustormerRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type LoraclientDeleteCustomerRequest struct {
	OrgID                int64    `protobuf:"varint,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoraclientDeleteCustomerRequest) Reset()         { *m = LoraclientDeleteCustomerRequest{} }
func (m *LoraclientDeleteCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*LoraclientDeleteCustomerRequest) ProtoMessage()    {}
func (*LoraclientDeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_loraclient_7b174a694fa68362, []int{3}
}
func (m *LoraclientDeleteCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraclientDeleteCustomerRequest.Unmarshal(m, b)
}
func (m *LoraclientDeleteCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraclientDeleteCustomerRequest.Marshal(b, m, deterministic)
}
func (dst *LoraclientDeleteCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraclientDeleteCustomerRequest.Merge(dst, src)
}
func (m *LoraclientDeleteCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_LoraclientDeleteCustomerRequest.Size(m)
}
func (m *LoraclientDeleteCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraclientDeleteCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoraclientDeleteCustomerRequest proto.InternalMessageInfo

func (m *LoraclientDeleteCustomerRequest) GetOrgID() int64 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *LoraclientDeleteCustomerRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type LoraclientSensor struct {
	OrgDisplayName       string   `protobuf:"bytes,1,opt,name=OrgDisplayName,proto3" json:"OrgDisplayName,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	DevEUI               string   `protobuf:"bytes,4,opt,name=DevEUI,proto3" json:"DevEUI,omitempty"`
	AppKey               string   `protobuf:"bytes,5,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoraclientSensor) Reset()         { *m = LoraclientSensor{} }
func (m *LoraclientSensor) String() string { return proto.CompactTextString(m) }
func (*LoraclientSensor) ProtoMessage()    {}
func (*LoraclientSensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_loraclient_7b174a694fa68362, []int{4}
}
func (m *LoraclientSensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraclientSensor.Unmarshal(m, b)
}
func (m *LoraclientSensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraclientSensor.Marshal(b, m, deterministic)
}
func (dst *LoraclientSensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraclientSensor.Merge(dst, src)
}
func (m *LoraclientSensor) XXX_Size() int {
	return xxx_messageInfo_LoraclientSensor.Size(m)
}
func (m *LoraclientSensor) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraclientSensor.DiscardUnknown(m)
}

var xxx_messageInfo_LoraclientSensor proto.InternalMessageInfo

func (m *LoraclientSensor) GetOrgDisplayName() string {
	if m != nil {
		return m.OrgDisplayName
	}
	return ""
}

func (m *LoraclientSensor) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LoraclientSensor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoraclientSensor) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *LoraclientSensor) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func init() {
	proto.RegisterType((*LoraclientCustormer)(nil), "protos.LoraclientCustormer")
	proto.RegisterType((*LoraclientAddCustormerResponse)(nil), "protos.LoraclientAddCustormerResponse")
	proto.RegisterType((*LoraclientUpdateCustormerRequest)(nil), "protos.LoraclientUpdateCustormerRequest")
	proto.RegisterType((*LoraclientDeleteCustomerRequest)(nil), "protos.LoraclientDeleteCustomerRequest")
	proto.RegisterType((*LoraclientSensor)(nil), "protos.LoraclientSensor")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoraclientServiceClient is the client API for LoraclientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoraclientServiceClient interface {
	AddCustmoer(ctx context.Context, in *LoraclientCustormer, opts ...grpc.CallOption) (*LoraclientAddCustormerResponse, error)
	UpdateCustomer(ctx context.Context, in *LoraclientUpdateCustormerRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteCustmoer(ctx context.Context, in *LoraclientDeleteCustomerRequest, opts ...grpc.CallOption) (*Empty, error)
	AddSensor(ctx context.Context, in *LoraclientSensor, opts ...grpc.CallOption) (*Empty, error)
	UpdateSensor(ctx context.Context, in *LoraclientSensor, opts ...grpc.CallOption) (*Empty, error)
	DeleteSensor(ctx context.Context, in *LoraclientSensor, opts ...grpc.CallOption) (*Empty, error)
}

type loraclientServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoraclientServiceClient(cc *grpc.ClientConn) LoraclientServiceClient {
	return &loraclientServiceClient{cc}
}

func (c *loraclientServiceClient) AddCustmoer(ctx context.Context, in *LoraclientCustormer, opts ...grpc.CallOption) (*LoraclientAddCustormerResponse, error) {
	out := new(LoraclientAddCustormerResponse)
	err := c.cc.Invoke(ctx, "/protos.LoraclientService/AddCustmoer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loraclientServiceClient) UpdateCustomer(ctx context.Context, in *LoraclientUpdateCustormerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.LoraclientService/UpdateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loraclientServiceClient) DeleteCustmoer(ctx context.Context, in *LoraclientDeleteCustomerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.LoraclientService/DeleteCustmoer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loraclientServiceClient) AddSensor(ctx context.Context, in *LoraclientSensor, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.LoraclientService/AddSensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loraclientServiceClient) UpdateSensor(ctx context.Context, in *LoraclientSensor, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.LoraclientService/UpdateSensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loraclientServiceClient) DeleteSensor(ctx context.Context, in *LoraclientSensor, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.LoraclientService/DeleteSensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoraclientServiceServer is the server API for LoraclientService service.
type LoraclientServiceServer interface {
	AddCustmoer(context.Context, *LoraclientCustormer) (*LoraclientAddCustormerResponse, error)
	UpdateCustomer(context.Context, *LoraclientUpdateCustormerRequest) (*Empty, error)
	DeleteCustmoer(context.Context, *LoraclientDeleteCustomerRequest) (*Empty, error)
	AddSensor(context.Context, *LoraclientSensor) (*Empty, error)
	UpdateSensor(context.Context, *LoraclientSensor) (*Empty, error)
	DeleteSensor(context.Context, *LoraclientSensor) (*Empty, error)
}

func RegisterLoraclientServiceServer(s *grpc.Server, srv LoraclientServiceServer) {
	s.RegisterService(&_LoraclientService_serviceDesc, srv)
}

func _LoraclientService_AddCustmoer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoraclientCustormer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoraclientServiceServer).AddCustmoer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.LoraclientService/AddCustmoer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoraclientServiceServer).AddCustmoer(ctx, req.(*LoraclientCustormer))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoraclientService_UpdateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoraclientUpdateCustormerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoraclientServiceServer).UpdateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.LoraclientService/UpdateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoraclientServiceServer).UpdateCustomer(ctx, req.(*LoraclientUpdateCustormerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoraclientService_DeleteCustmoer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoraclientDeleteCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoraclientServiceServer).DeleteCustmoer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.LoraclientService/DeleteCustmoer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoraclientServiceServer).DeleteCustmoer(ctx, req.(*LoraclientDeleteCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoraclientService_AddSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoraclientSensor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoraclientServiceServer).AddSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.LoraclientService/AddSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoraclientServiceServer).AddSensor(ctx, req.(*LoraclientSensor))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoraclientService_UpdateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoraclientSensor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoraclientServiceServer).UpdateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.LoraclientService/UpdateSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoraclientServiceServer).UpdateSensor(ctx, req.(*LoraclientSensor))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoraclientService_DeleteSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoraclientSensor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoraclientServiceServer).DeleteSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.LoraclientService/DeleteSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoraclientServiceServer).DeleteSensor(ctx, req.(*LoraclientSensor))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoraclientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.LoraclientService",
	HandlerType: (*LoraclientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCustmoer",
			Handler:    _LoraclientService_AddCustmoer_Handler,
		},
		{
			MethodName: "UpdateCustomer",
			Handler:    _LoraclientService_UpdateCustomer_Handler,
		},
		{
			MethodName: "DeleteCustmoer",
			Handler:    _LoraclientService_DeleteCustmoer_Handler,
		},
		{
			MethodName: "AddSensor",
			Handler:    _LoraclientService_AddSensor_Handler,
		},
		{
			MethodName: "UpdateSensor",
			Handler:    _LoraclientService_UpdateSensor_Handler,
		},
		{
			MethodName: "DeleteSensor",
			Handler:    _LoraclientService_DeleteSensor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loraclient",
}

func init() { proto.RegisterFile("loraclient", fileDescriptor_loraclient_7b174a694fa68362) }

var fileDescriptor_loraclient_7b174a694fa68362 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0x4d, 0x5b, 0xed, 0xf4, 0x07, 0x5d, 0x45, 0x42, 0x04, 0x2d, 0x3d, 0xd4, 0x9e, 0x7a,
	0x50, 0xc1, 0x73, 0x31, 0x05, 0x83, 0xd2, 0x48, 0xb4, 0x0f, 0x10, 0x9b, 0xa5, 0x14, 0x92, 0xec,
	0xba, 0x9b, 0x56, 0xf2, 0x0c, 0xde, 0x7c, 0x06, 0x9f, 0xc5, 0xe7, 0x92, 0xec, 0x26, 0x4d, 0xda,
	0xa4, 0x14, 0xbd, 0xe5, 0xdb, 0x99, 0xf9, 0xf8, 0xe6, 0x9b, 0x8f, 0x00, 0x78, 0x84, 0x39, 0x33,
	0x6f, 0x81, 0x83, 0x10, 0xd5, 0x29, 0x23, 0x21, 0xe1, 0x7a, 0x7d, 0x46, 0x7c, 0x9f, 0x04, 0xbd,
	0x4f, 0x05, 0x4e, 0x9e, 0xd6, 0xe5, 0xfb, 0x25, 0x0f, 0x09, 0xf3, 0x31, 0x43, 0x1a, 0x1c, 0x58,
	0x6c, 0x3e, 0x71, 0x7c, 0xac, 0x29, 0x5d, 0x65, 0xd0, 0xb0, 0x53, 0x88, 0xfa, 0xd0, 0xb1, 0xd8,
	0xdc, 0x58, 0x70, 0xea, 0x39, 0x91, 0x68, 0xa8, 0x88, 0x86, 0xad, 0x57, 0xa4, 0xc3, 0xe1, 0x94,
	0x63, 0x26, 0x3a, 0x54, 0xd1, 0xb1, 0xc6, 0xe8, 0x0c, 0xea, 0xcf, 0x0e, 0xe7, 0x1f, 0xae, 0x56,
	0x15, 0x95, 0x04, 0xf5, 0x26, 0x70, 0x91, 0x89, 0x19, 0xb9, 0xee, 0x5a, 0x8f, 0x8d, 0x39, 0x25,
	0x01, 0xc7, 0xe8, 0x14, 0x6a, 0x16, 0x9b, 0x9b, 0x86, 0x50, 0xa5, 0xda, 0x12, 0xc4, 0x7c, 0x31,
	0xb7, 0x69, 0x08, 0x2d, 0xaa, 0x9d, 0xa0, 0xde, 0x8f, 0x02, 0xdd, 0x8c, 0x70, 0x4a, 0x5d, 0x27,
	0xc4, 0x39, 0xce, 0xf7, 0x25, 0xe6, 0xe1, 0x0e, 0xca, 0x9c, 0x01, 0x95, 0x7d, 0x06, 0xa8, 0xa5,
	0x06, 0x64, 0xa2, 0x9a, 0x79, 0x51, 0x1b, 0xc6, 0xb4, 0x76, 0x1a, 0xd3, 0xde, 0x30, 0xc6, 0x82,
	0xcb, 0x6c, 0x0f, 0x03, 0x7b, 0x38, 0xd9, 0x63, 0xef, 0x1a, 0xbb, 0x9c, 0xf9, 0x52, 0xe0, 0x28,
	0x63, 0x7c, 0xc1, 0x01, 0x27, 0xac, 0x64, 0x33, 0xa5, 0x74, 0x33, 0x04, 0xd5, 0xd7, 0x88, 0xa6,
	0xc6, 0x88, 0xef, 0xf8, 0x2d, 0xe7, 0x45, 0x35, 0xdd, 0xc6, 0xc0, 0xab, 0xf1, 0xd4, 0x4c, 0xcf,
	0x2c, 0x51, 0xfc, 0x3e, 0xa2, 0xf4, 0x11, 0x47, 0x5a, 0x4d, 0xbe, 0x4b, 0x74, 0xfd, 0xad, 0xc2,
	0x71, 0x5e, 0x14, 0x5b, 0x2d, 0x66, 0x18, 0xd9, 0xd0, 0x4c, 0xa2, 0xe0, 0x13, 0xcc, 0xd0, 0xf9,
	0x50, 0x46, 0x78, 0x58, 0x12, 0x5b, 0xbd, 0x5f, 0x2c, 0x96, 0xc6, 0xc8, 0x84, 0x4e, 0x2e, 0x0d,
	0x71, 0xe0, 0x07, 0xc5, 0xc9, 0xf2, 0xbc, 0xe8, 0xed, 0xb4, 0x73, 0xec, 0xd3, 0x30, 0x42, 0x0f,
	0xd0, 0xc9, 0x0e, 0x22, 0x14, 0x5e, 0x15, 0xa9, 0x4a, 0x4f, 0xb6, 0xcd, 0x74, 0x0b, 0x8d, 0x91,
	0xeb, 0x26, 0xb7, 0xd0, 0x8a, 0x24, 0xb2, 0xb2, 0x3d, 0x75, 0x07, 0x2d, 0x29, 0xf4, 0x1f, 0x83,
	0x52, 0xd6, 0x1f, 0x07, 0xdf, 0xe4, 0x3f, 0xe4, 0xe6, 0x37, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x9b,
	0x7b, 0x06, 0x58, 0x04, 0x00, 0x00,
}
