// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Manager struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Passwd               string   `protobuf:"bytes,3,opt,name=Passwd,proto3" json:"Passwd,omitempty"`
	DisplayName          string   `protobuf:"bytes,4,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	RoleID               uint64   `protobuf:"varint,6,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manager) Reset()         { *m = Manager{} }
func (m *Manager) String() string { return proto.CompactTextString(m) }
func (*Manager) ProtoMessage()    {}
func (*Manager) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_4994799575eda0a3, []int{0}
}
func (m *Manager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manager.Unmarshal(m, b)
}
func (m *Manager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manager.Marshal(b, m, deterministic)
}
func (dst *Manager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager.Merge(dst, src)
}
func (m *Manager) XXX_Size() int {
	return xxx_messageInfo_Manager.Size(m)
}
func (m *Manager) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager.DiscardUnknown(m)
}

var xxx_messageInfo_Manager proto.InternalMessageInfo

func (m *Manager) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Manager) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Manager) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *Manager) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Manager) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Manager) GetRoleID() uint64 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

type ManagerLoginRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerLoginRequest) Reset()         { *m = ManagerLoginRequest{} }
func (m *ManagerLoginRequest) String() string { return proto.CompactTextString(m) }
func (*ManagerLoginRequest) ProtoMessage()    {}
func (*ManagerLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_4994799575eda0a3, []int{1}
}
func (m *ManagerLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerLoginRequest.Unmarshal(m, b)
}
func (m *ManagerLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerLoginRequest.Marshal(b, m, deterministic)
}
func (dst *ManagerLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerLoginRequest.Merge(dst, src)
}
func (m *ManagerLoginRequest) XXX_Size() int {
	return xxx_messageInfo_ManagerLoginRequest.Size(m)
}
func (m *ManagerLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerLoginRequest proto.InternalMessageInfo

func (m *ManagerLoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ManagerLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ManagerLoginResponse struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	RoleID               uint64   `protobuf:"varint,3,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerLoginResponse) Reset()         { *m = ManagerLoginResponse{} }
func (m *ManagerLoginResponse) String() string { return proto.CompactTextString(m) }
func (*ManagerLoginResponse) ProtoMessage()    {}
func (*ManagerLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_4994799575eda0a3, []int{2}
}
func (m *ManagerLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerLoginResponse.Unmarshal(m, b)
}
func (m *ManagerLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerLoginResponse.Marshal(b, m, deterministic)
}
func (dst *ManagerLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerLoginResponse.Merge(dst, src)
}
func (m *ManagerLoginResponse) XXX_Size() int {
	return xxx_messageInfo_ManagerLoginResponse.Size(m)
}
func (m *ManagerLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerLoginResponse proto.InternalMessageInfo

func (m *ManagerLoginResponse) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ManagerLoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ManagerLoginResponse) GetRoleID() uint64 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func init() {
	proto.RegisterType((*Manager)(nil), "protos.Manager")
	proto.RegisterType((*ManagerLoginRequest)(nil), "protos.ManagerLoginRequest")
	proto.RegisterType((*ManagerLoginResponse)(nil), "protos.ManagerLoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerServiceClient interface {
	Login(ctx context.Context, in *ManagerLoginRequest, opts ...grpc.CallOption) (*ManagerLoginResponse, error)
}

type managerServiceClient struct {
	cc *grpc.ClientConn
}

func NewManagerServiceClient(cc *grpc.ClientConn) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) Login(ctx context.Context, in *ManagerLoginRequest, opts ...grpc.CallOption) (*ManagerLoginResponse, error) {
	out := new(ManagerLoginResponse)
	err := c.cc.Invoke(ctx, "/protos.ManagerService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
type ManagerServiceServer interface {
	Login(context.Context, *ManagerLoginRequest) (*ManagerLoginResponse, error)
}

func RegisterManagerServiceServer(s *grpc.Server, srv ManagerServiceServer) {
	s.RegisterService(&_ManagerService_serviceDesc, srv)
}

func _ManagerService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ManagerService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Login(ctx, req.(*ManagerLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _ManagerService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager",
}

func init() { proto.RegisterFile("manager", fileDescriptor_manager_4994799575eda0a3) }

var fileDescriptor_manager_4994799575eda0a3 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xc9, 0x76, 0x77, 0xab, 0x23, 0xf4, 0x30, 0x16, 0x09, 0xd5, 0xc3, 0xb2, 0xa7, 0x9e,
	0x7a, 0xd0, 0x37, 0x90, 0xbd, 0x2c, 0x58, 0x29, 0x51, 0x1f, 0x20, 0xda, 0xa1, 0x2e, 0xb4, 0xc9,
	0x9a, 0xa9, 0x8a, 0x0f, 0xe2, 0xfb, 0x4a, 0x27, 0xa1, 0x54, 0xe8, 0xa1, 0xb7, 0xfc, 0xff, 0x4f,
	0xfe, 0xf9, 0x26, 0x81, 0xe1, 0xc6, 0x3a, 0xbb, 0xa2, 0x80, 0x65, 0x1f, 0xfc, 0xd6, 0x73, 0xfd,
	0xab, 0x60, 0x38, 0x4f, 0xde, 0x08, 0xb2, 0xb6, 0xd1, 0xaa, 0x52, 0xd3, 0xdc, 0x64, 0x6d, 0x83,
	0x08, 0xf9, 0xa3, 0xdd, 0x90, 0xce, 0x2a, 0x35, 0x3d, 0x37, 0x72, 0xc6, 0x2b, 0x28, 0x17, 0x96,
	0xf9, 0x7b, 0xa9, 0x07, 0xe2, 0x26, 0x85, 0x15, 0x5c, 0x34, 0x1d, 0xf7, 0x6b, 0xfb, 0x23, 0x57,
	0x72, 0x09, 0x0f, 0x2d, 0x1c, 0x43, 0xb1, 0x78, 0xf7, 0x8e, 0x74, 0x21, 0x59, 0x14, 0xbb, 0x3e,
	0xe3, 0xd7, 0xd4, 0x36, 0xba, 0x94, 0xb9, 0x49, 0xd5, 0x73, 0xb8, 0x4c, 0x58, 0x0f, 0x7e, 0xd5,
	0x39, 0x43, 0x1f, 0x9f, 0xc4, 0x5b, 0x9c, 0xc0, 0xd9, 0x0b, 0x53, 0x90, 0x19, 0x4a, 0x7a, 0xf6,
	0x7a, 0x97, 0x09, 0x8c, 0x0f, 0xcb, 0x84, 0xbc, 0xd7, 0xb5, 0x81, 0xf1, 0xff, 0x3a, 0xee, 0xbd,
	0x63, 0x3a, 0x75, 0xe5, 0x84, 0x38, 0x38, 0x44, 0xbc, 0x7d, 0x86, 0x51, 0xea, 0x7c, 0xa2, 0xf0,
	0xd5, 0xbd, 0x11, 0xde, 0x43, 0x21, 0xf5, 0x78, 0x3d, 0x8b, 0xcf, 0x3b, 0x3b, 0xb2, 0xc3, 0xe4,
	0xe6, 0x78, 0x18, 0x89, 0x5e, 0xe3, 0xc7, 0xdc, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xa1,
	0x99, 0x83, 0xaa, 0x01, 0x00, 0x00,
}
