// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manufacturer

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Manufacturer struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Manufacturer) Reset()         { *m = Manufacturer{} }
func (m *Manufacturer) String() string { return proto.CompactTextString(m) }
func (*Manufacturer) ProtoMessage()    {}
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return fileDescriptor_manufacturer_4a19cb01b702419f, []int{0}
}
func (m *Manufacturer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manufacturer.Unmarshal(m, b)
}
func (m *Manufacturer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manufacturer.Marshal(b, m, deterministic)
}
func (dst *Manufacturer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manufacturer.Merge(dst, src)
}
func (m *Manufacturer) XXX_Size() int {
	return xxx_messageInfo_Manufacturer.Size(m)
}
func (m *Manufacturer) XXX_DiscardUnknown() {
	xxx_messageInfo_Manufacturer.DiscardUnknown(m)
}

var xxx_messageInfo_Manufacturer proto.InternalMessageInfo

func (m *Manufacturer) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Manufacturer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ManufacturerList struct {
	List                 []*Manufacturer `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64          `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ManufacturerList) Reset()         { *m = ManufacturerList{} }
func (m *ManufacturerList) String() string { return proto.CompactTextString(m) }
func (*ManufacturerList) ProtoMessage()    {}
func (*ManufacturerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_manufacturer_4a19cb01b702419f, []int{1}
}
func (m *ManufacturerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManufacturerList.Unmarshal(m, b)
}
func (m *ManufacturerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManufacturerList.Marshal(b, m, deterministic)
}
func (dst *ManufacturerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManufacturerList.Merge(dst, src)
}
func (m *ManufacturerList) XXX_Size() int {
	return xxx_messageInfo_ManufacturerList.Size(m)
}
func (m *ManufacturerList) XXX_DiscardUnknown() {
	xxx_messageInfo_ManufacturerList.DiscardUnknown(m)
}

var xxx_messageInfo_ManufacturerList proto.InternalMessageInfo

func (m *ManufacturerList) GetList() []*Manufacturer {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ManufacturerList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetManufacturersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetManufacturersRequest) Reset()         { *m = GetManufacturersRequest{} }
func (m *GetManufacturersRequest) String() string { return proto.CompactTextString(m) }
func (*GetManufacturersRequest) ProtoMessage()    {}
func (*GetManufacturersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_manufacturer_4a19cb01b702419f, []int{2}
}
func (m *GetManufacturersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetManufacturersRequest.Unmarshal(m, b)
}
func (m *GetManufacturersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetManufacturersRequest.Marshal(b, m, deterministic)
}
func (dst *GetManufacturersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetManufacturersRequest.Merge(dst, src)
}
func (m *GetManufacturersRequest) XXX_Size() int {
	return xxx_messageInfo_GetManufacturersRequest.Size(m)
}
func (m *GetManufacturersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetManufacturersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetManufacturersRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Manufacturer)(nil), "protos.Manufacturer")
	proto.RegisterType((*ManufacturerList)(nil), "protos.ManufacturerList")
	proto.RegisterType((*GetManufacturersRequest)(nil), "protos.GetManufacturersRequest")
}

func init() { proto.RegisterFile("manufacturer", fileDescriptor_manufacturer_4a19cb01b702419f) }

var fileDescriptor_manufacturer_4a19cb01b702419f = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4d, 0xcc, 0x2b,
	0x4d, 0x4b, 0x4c, 0x2e, 0x29, 0x2d, 0x4a, 0x2d, 0x12, 0x62, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x2f,
	0x56, 0x32, 0xe2, 0xe2, 0xf1, 0x45, 0x16, 0xe7, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x09, 0x62, 0xf2, 0x74, 0x11, 0x12, 0xe2, 0x62, 0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x82, 0xb8, 0x04, 0x90, 0xf5, 0xf8, 0x64, 0x16,
	0x97, 0x08, 0x69, 0x70, 0xb1, 0x80, 0x68, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x11, 0x3d,
	0x88, 0xf1, 0x7a, 0xc8, 0xea, 0x82, 0xc0, 0x2a, 0x84, 0x44, 0xb8, 0x58, 0x9d, 0xf3, 0x4b, 0xf3,
	0x4a, 0xc0, 0x46, 0xb2, 0x04, 0x41, 0x38, 0x4a, 0x92, 0x5c, 0xe2, 0xee, 0xa9, 0x25, 0xc8, 0xca,
	0x8b, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x92, 0x20, 0x4e, 0x35, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x99, 0xb4, 0xda, 0x77, 0xc1, 0x00, 0x00, 0x00,
}
