// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_management

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotificationInfo struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeviceName           string   `protobuf:"bytes,2,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	DeviceSerialNumber   string   `protobuf:"bytes,3,opt,name=DeviceSerialNumber,proto3" json:"DeviceSerialNumber,omitempty"`
	DeviceType           string   `protobuf:"bytes,4,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	DeviceTypeID         uint64   `protobuf:"varint,5,opt,name=DeviceTypeID,proto3" json:"DeviceTypeID,omitempty"`
	DeviceModel          string   `protobuf:"bytes,6,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
	DeviceModelID        uint64   `protobuf:"varint,7,opt,name=DeviceModelID,proto3" json:"DeviceModelID,omitempty"`
	Group                string   `protobuf:"bytes,8,opt,name=Group,proto3" json:"Group,omitempty"`
	GroupID              uint64   `protobuf:"varint,9,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Content              string   `protobuf:"bytes,11,opt,name=Content,proto3" json:"Content,omitempty"`
	Solved               string   `protobuf:"bytes,12,opt,name=Solved,proto3" json:"Solved,omitempty"`
	SolvedAt             string   `protobuf:"bytes,13,opt,name=SolvedAt,proto3" json:"SolvedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationInfo) Reset()         { *m = NotificationInfo{} }
func (m *NotificationInfo) String() string { return proto.CompactTextString(m) }
func (*NotificationInfo) ProtoMessage()    {}
func (*NotificationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_management_fc2db1902451f350, []int{0}
}
func (m *NotificationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationInfo.Unmarshal(m, b)
}
func (m *NotificationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationInfo.Marshal(b, m, deterministic)
}
func (dst *NotificationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationInfo.Merge(dst, src)
}
func (m *NotificationInfo) XXX_Size() int {
	return xxx_messageInfo_NotificationInfo.Size(m)
}
func (m *NotificationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationInfo proto.InternalMessageInfo

func (m *NotificationInfo) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NotificationInfo) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *NotificationInfo) GetDeviceSerialNumber() string {
	if m != nil {
		return m.DeviceSerialNumber
	}
	return ""
}

func (m *NotificationInfo) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *NotificationInfo) GetDeviceTypeID() uint64 {
	if m != nil {
		return m.DeviceTypeID
	}
	return 0
}

func (m *NotificationInfo) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *NotificationInfo) GetDeviceModelID() uint64 {
	if m != nil {
		return m.DeviceModelID
	}
	return 0
}

func (m *NotificationInfo) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *NotificationInfo) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *NotificationInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotificationInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NotificationInfo) GetSolved() string {
	if m != nil {
		return m.Solved
	}
	return ""
}

func (m *NotificationInfo) GetSolvedAt() string {
	if m != nil {
		return m.SolvedAt
	}
	return ""
}

type NotificationList struct {
	List                 []*NotificationInfo `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64              `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	CurrentPage          uint64              `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64              `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64              `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NotificationList) Reset()         { *m = NotificationList{} }
func (m *NotificationList) String() string { return proto.CompactTextString(m) }
func (*NotificationList) ProtoMessage()    {}
func (*NotificationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_management_fc2db1902451f350, []int{1}
}
func (m *NotificationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationList.Unmarshal(m, b)
}
func (m *NotificationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationList.Marshal(b, m, deterministic)
}
func (dst *NotificationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationList.Merge(dst, src)
}
func (m *NotificationList) XXX_Size() int {
	return xxx_messageInfo_NotificationList.Size(m)
}
func (m *NotificationList) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationList.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationList proto.InternalMessageInfo

func (m *NotificationList) GetList() []*NotificationInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *NotificationList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *NotificationList) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *NotificationList) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *NotificationList) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*NotificationInfo)(nil), "protos.NotificationInfo")
	proto.RegisterType((*NotificationList)(nil), "protos.NotificationList")
}

func init() {
	proto.RegisterFile("message_management", fileDescriptor_message_management_fc2db1902451f350)
}

var fileDescriptor_message_management_fc2db1902451f350 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xd6, 0xfd, 0x3b, 0xdb, 0x44, 0x82, 0xc8, 0x41, 0x44, 0xca, 0xf0, 0x62, 0x17,
	0xb2, 0x0b, 0x7d, 0x82, 0xd1, 0x82, 0x14, 0x74, 0x48, 0xb7, 0x7b, 0xc9, 0xb6, 0xb3, 0x51, 0x68,
	0x93, 0xd1, 0xa6, 0x03, 0x7d, 0x14, 0x9f, 0xc3, 0x07, 0x94, 0x9c, 0xb8, 0xad, 0x13, 0xaf, 0x92,
	0xdf, 0xf7, 0x25, 0x1f, 0x39, 0xfd, 0x0a, 0x22, 0xa7, 0xb2, 0x94, 0x5b, 0x7a, 0xcf, 0xa5, 0x92,
	0x5b, 0xca, 0x49, 0x19, 0xd1, 0xde, 0x15, 0xda, 0xe8, 0x72, 0xf4, 0xd5, 0x84, 0xcb, 0x99, 0x36,
	0xe9, 0x26, 0x5d, 0x49, 0x93, 0x6a, 0x15, 0xab, 0x8d, 0x16, 0x17, 0xd0, 0x88, 0x23, 0xf4, 0x02,
	0x6f, 0xec, 0x27, 0x8d, 0x38, 0x12, 0x77, 0x00, 0x11, 0xed, 0xd3, 0x15, 0xcd, 0x64, 0x4e, 0xd8,
	0x08, 0xbc, 0x71, 0x2f, 0xa9, 0x29, 0x62, 0x02, 0xc2, 0xd1, 0x9c, 0x8a, 0x54, 0x66, 0xb3, 0x2a,
	0x5f, 0x52, 0x81, 0x4d, 0x3e, 0xf7, 0x8f, 0x73, 0xca, 0x5b, 0x7c, 0xec, 0x08, 0xfd, 0x7a, 0x9e,
	0x55, 0xc4, 0x08, 0x06, 0x27, 0x8a, 0x23, 0x6c, 0xf1, 0x4b, 0xce, 0x34, 0x11, 0x40, 0xdf, 0xf1,
	0xab, 0x5e, 0x53, 0x86, 0x6d, 0x0e, 0xa9, 0x4b, 0xe2, 0x1e, 0x86, 0x35, 0x8c, 0x23, 0xec, 0x70,
	0xcc, 0xb9, 0x28, 0xae, 0xa0, 0xf5, 0x5c, 0xe8, 0x6a, 0x87, 0x5d, 0x4e, 0x70, 0x20, 0x10, 0x3a,
	0xbc, 0x89, 0x23, 0xec, 0xf1, 0xad, 0x03, 0x8a, 0x5b, 0xe8, 0x85, 0x05, 0x49, 0x43, 0xeb, 0xa9,
	0x41, 0xe0, 0x3b, 0x27, 0xc1, 0xde, 0x0b, 0xb5, 0x32, 0xa4, 0x0c, 0xf6, 0xd9, 0x3b, 0xa0, 0xb8,
	0x86, 0xf6, 0x5c, 0x67, 0x7b, 0x5a, 0xe3, 0x80, 0x8d, 0x5f, 0x12, 0x37, 0xd0, 0x75, 0xbb, 0xa9,
	0xc1, 0x21, 0x3b, 0x47, 0x1e, 0x7d, 0x7b, 0xe7, 0xe5, 0xbc, 0xa4, 0xa5, 0x11, 0x0f, 0xe0, 0xdb,
	0x15, 0xbd, 0xa0, 0x39, 0xee, 0x3f, 0xe2, 0xc4, 0x15, 0x39, 0xf9, 0x5b, 0x62, 0xc2, 0xa7, 0xec,
	0x78, 0xa1, 0xae, 0x94, 0xe1, 0xd6, 0xfc, 0xc4, 0x81, 0xfd, 0x78, 0x61, 0x55, 0x14, 0xa4, 0xcc,
	0x9b, 0xdc, 0x12, 0x8f, 0xe1, 0x27, 0x75, 0xc9, 0x3e, 0xcb, 0xae, 0xf3, 0xf4, 0x93, 0x78, 0x12,
	0x3f, 0x39, 0xb2, 0xad, 0x6f, 0xa1, 0x8d, 0xcc, 0x5c, 0xf0, 0x80, 0xdd, 0x9a, 0xb2, 0x74, 0xff,
	0xd6, 0xd3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x27, 0x05, 0x7e, 0x78, 0x02, 0x00, 0x00,
}
