// Code generated by protoc-gen-go. DO NOT EDIT.
// source: parser

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("parser", fileDescriptor_parser_d8fe665476370be7) }

var fileDescriptor_parser_d8fe665476370be7 = []byte{
	// 44 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x2b, 0x48, 0x2c, 0x2a,
	0x4e, 0x2d, 0x12, 0x62, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0x4e, 0x82, 0xd0, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x64, 0x7f, 0xa6, 0xa5, 0x18, 0x00, 0x00, 0x00,
}
