// Code generated by protoc-gen-go. DO NOT EDIT.
// source: parserhub

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// lora-app-server的DataUpPayload结构, 上行信息的回调请求数据
type ParserHubUplinkMsg struct {
	ApplicationID        string   `protobuf:"bytes,1,opt,name=applicationID,proto3" json:"applicationID,omitempty"`
	ApplicationName      string   `protobuf:"bytes,2,opt,name=applicationName,proto3" json:"applicationName,omitempty"`
	DeviceName           string   `protobuf:"bytes,3,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	DevEUI               string   `protobuf:"bytes,4,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	DeviceStatusBattery  string   `protobuf:"bytes,5,opt,name=deviceStatusBattery,proto3" json:"deviceStatusBattery,omitempty"`
	DeviceStatusMargin   string   `protobuf:"bytes,6,opt,name=deviceStatusMargin,proto3" json:"deviceStatusMargin,omitempty"`
	FPort                uint32   `protobuf:"varint,7,opt,name=fPort,proto3" json:"fPort,omitempty"`
	Data                 string   `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	FinalData            []byte   `protobuf:"bytes,20,opt,name=FinalData,proto3" json:"FinalData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserHubUplinkMsg) Reset()         { *m = ParserHubUplinkMsg{} }
func (m *ParserHubUplinkMsg) String() string { return proto.CompactTextString(m) }
func (*ParserHubUplinkMsg) ProtoMessage()    {}
func (*ParserHubUplinkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_parserhub_527b94bbecd2e2d6, []int{0}
}
func (m *ParserHubUplinkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserHubUplinkMsg.Unmarshal(m, b)
}
func (m *ParserHubUplinkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserHubUplinkMsg.Marshal(b, m, deterministic)
}
func (dst *ParserHubUplinkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserHubUplinkMsg.Merge(dst, src)
}
func (m *ParserHubUplinkMsg) XXX_Size() int {
	return xxx_messageInfo_ParserHubUplinkMsg.Size(m)
}
func (m *ParserHubUplinkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserHubUplinkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ParserHubUplinkMsg proto.InternalMessageInfo

func (m *ParserHubUplinkMsg) GetApplicationID() string {
	if m != nil {
		return m.ApplicationID
	}
	return ""
}

func (m *ParserHubUplinkMsg) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *ParserHubUplinkMsg) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *ParserHubUplinkMsg) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *ParserHubUplinkMsg) GetDeviceStatusBattery() string {
	if m != nil {
		return m.DeviceStatusBattery
	}
	return ""
}

func (m *ParserHubUplinkMsg) GetDeviceStatusMargin() string {
	if m != nil {
		return m.DeviceStatusMargin
	}
	return ""
}

func (m *ParserHubUplinkMsg) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *ParserHubUplinkMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ParserHubUplinkMsg) GetFinalData() []byte {
	if m != nil {
		return m.FinalData
	}
	return nil
}

type ParserHubUplinkMsgPayload struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserHubUplinkMsgPayload) Reset()         { *m = ParserHubUplinkMsgPayload{} }
func (m *ParserHubUplinkMsgPayload) String() string { return proto.CompactTextString(m) }
func (*ParserHubUplinkMsgPayload) ProtoMessage()    {}
func (*ParserHubUplinkMsgPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_parserhub_527b94bbecd2e2d6, []int{1}
}
func (m *ParserHubUplinkMsgPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserHubUplinkMsgPayload.Unmarshal(m, b)
}
func (m *ParserHubUplinkMsgPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserHubUplinkMsgPayload.Marshal(b, m, deterministic)
}
func (dst *ParserHubUplinkMsgPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserHubUplinkMsgPayload.Merge(dst, src)
}
func (m *ParserHubUplinkMsgPayload) XXX_Size() int {
	return xxx_messageInfo_ParserHubUplinkMsgPayload.Size(m)
}
func (m *ParserHubUplinkMsgPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserHubUplinkMsgPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ParserHubUplinkMsgPayload proto.InternalMessageInfo

func (m *ParserHubUplinkMsgPayload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ParserHubDecodedMsg struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserHubDecodedMsg) Reset()         { *m = ParserHubDecodedMsg{} }
func (m *ParserHubDecodedMsg) String() string { return proto.CompactTextString(m) }
func (*ParserHubDecodedMsg) ProtoMessage()    {}
func (*ParserHubDecodedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_parserhub_527b94bbecd2e2d6, []int{2}
}
func (m *ParserHubDecodedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserHubDecodedMsg.Unmarshal(m, b)
}
func (m *ParserHubDecodedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserHubDecodedMsg.Marshal(b, m, deterministic)
}
func (dst *ParserHubDecodedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserHubDecodedMsg.Merge(dst, src)
}
func (m *ParserHubDecodedMsg) XXX_Size() int {
	return xxx_messageInfo_ParserHubDecodedMsg.Size(m)
}
func (m *ParserHubDecodedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserHubDecodedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ParserHubDecodedMsg proto.InternalMessageInfo

func (m *ParserHubDecodedMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ParserHealthCheckResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParserHealthCheckResponse) Reset()         { *m = ParserHealthCheckResponse{} }
func (m *ParserHealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*ParserHealthCheckResponse) ProtoMessage()    {}
func (*ParserHealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_parserhub_527b94bbecd2e2d6, []int{3}
}
func (m *ParserHealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParserHealthCheckResponse.Unmarshal(m, b)
}
func (m *ParserHealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParserHealthCheckResponse.Marshal(b, m, deterministic)
}
func (dst *ParserHealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParserHealthCheckResponse.Merge(dst, src)
}
func (m *ParserHealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_ParserHealthCheckResponse.Size(m)
}
func (m *ParserHealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParserHealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParserHealthCheckResponse proto.InternalMessageInfo

func (m *ParserHealthCheckResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ParserHubUplinkMsg)(nil), "protos.ParserHubUplinkMsg")
	proto.RegisterType((*ParserHubUplinkMsgPayload)(nil), "protos.ParserHubUplinkMsgPayload")
	proto.RegisterType((*ParserHubDecodedMsg)(nil), "protos.ParserHubDecodedMsg")
	proto.RegisterType((*ParserHealthCheckResponse)(nil), "protos.ParserHealthCheckResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ParserHubServiceClient is the client API for ParserHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParserHubServiceClient interface {
	ParseAndSave(ctx context.Context, in *ParserHubUplinkMsg, opts ...grpc.CallOption) (*Empty, error)
}

type parserHubServiceClient struct {
	cc *grpc.ClientConn
}

func NewParserHubServiceClient(cc *grpc.ClientConn) ParserHubServiceClient {
	return &parserHubServiceClient{cc}
}

func (c *parserHubServiceClient) ParseAndSave(ctx context.Context, in *ParserHubUplinkMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.ParserHubService/ParseAndSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParserHubServiceServer is the server API for ParserHubService service.
type ParserHubServiceServer interface {
	ParseAndSave(context.Context, *ParserHubUplinkMsg) (*Empty, error)
}

func RegisterParserHubServiceServer(s *grpc.Server, srv ParserHubServiceServer) {
	s.RegisterService(&_ParserHubService_serviceDesc, srv)
}

func _ParserHubService_ParseAndSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParserHubUplinkMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserHubServiceServer).ParseAndSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ParserHubService/ParseAndSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserHubServiceServer).ParseAndSave(ctx, req.(*ParserHubUplinkMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _ParserHubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ParserHubService",
	HandlerType: (*ParserHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseAndSave",
			Handler:    _ParserHubService_ParseAndSave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parserhub",
}

func init() { proto.RegisterFile("parserhub", fileDescriptor_parserhub_527b94bbecd2e2d6) }

var fileDescriptor_parserhub_527b94bbecd2e2d6 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6a, 0xea, 0x50,
	0x10, 0xc6, 0x89, 0x7f, 0x72, 0x71, 0x50, 0xae, 0x8c, 0x72, 0xc9, 0x95, 0xcb, 0x45, 0x42, 0x17,
	0xe9, 0xa2, 0xb6, 0xb4, 0xab, 0x2e, 0xdb, 0x6a, 0xa9, 0x0b, 0x8b, 0x44, 0x7c, 0x80, 0x31, 0x99,
	0x6a, 0x30, 0xc9, 0x09, 0xe7, 0x1c, 0x05, 0x5f, 0xb0, 0xcf, 0x55, 0x72, 0x62, 0xd3, 0xb4, 0xba,
	0x9b, 0xf9, 0xbe, 0xdf, 0x37, 0xc9, 0x19, 0x06, 0x5a, 0x19, 0x49, 0xc5, 0x72, 0xb3, 0x5b, 0xa1,
	0x9d, 0x49, 0xa1, 0x85, 0x1a, 0xd8, 0x81, 0x48, 0x12, 0x91, 0xba, 0xef, 0x35, 0xc0, 0xb9, 0x71,
	0x5f, 0x76, 0xab, 0x65, 0x16, 0x47, 0xe9, 0x76, 0xa6, 0xd6, 0x78, 0x01, 0x1d, 0xca, 0xb2, 0x38,
	0x0a, 0x48, 0x47, 0x22, 0x9d, 0x8e, 0x1d, 0x6b, 0x68, 0x79, 0x2d, 0xff, 0xbb, 0x88, 0x1e, 0xfc,
	0xae, 0x08, 0xaf, 0x94, 0xb0, 0x53, 0x33, 0xdc, 0x4f, 0x19, 0xff, 0x03, 0x84, 0xbc, 0x8f, 0x02,
	0x36, 0x50, 0xdd, 0x40, 0x15, 0x05, 0xff, 0x80, 0x1d, 0xf2, 0x7e, 0xb2, 0x9c, 0x3a, 0x0d, 0xe3,
	0x1d, 0x3b, 0xbc, 0x81, 0x5e, 0x41, 0x2d, 0x34, 0xe9, 0x9d, 0x7a, 0x24, 0xad, 0x59, 0x1e, 0x9c,
	0xa6, 0x81, 0xce, 0x59, 0x38, 0x02, 0xac, 0xca, 0x33, 0x92, 0xeb, 0x28, 0x75, 0x6c, 0x13, 0x38,
	0xe3, 0x60, 0x1f, 0x9a, 0x6f, 0x73, 0x21, 0xb5, 0xf3, 0x6b, 0x68, 0x79, 0x1d, 0xbf, 0x68, 0x10,
	0xa1, 0x11, 0x92, 0x26, 0x07, 0x4c, 0xce, 0xd4, 0xf8, 0x0f, 0x5a, 0xcf, 0x51, 0x4a, 0xf1, 0x38,
	0x37, 0xfa, 0x43, 0xcb, 0x6b, 0xfb, 0x5f, 0x82, 0x7b, 0x0d, 0x7f, 0x4f, 0xf7, 0x38, 0xa7, 0x43,
	0x2c, 0x28, 0x2c, 0xc7, 0x59, 0x26, 0x65, 0x6a, 0xf7, 0x12, 0x7a, 0x65, 0x60, 0xcc, 0x81, 0x08,
	0x39, 0xcc, 0x37, 0x5f, 0x45, 0x8f, 0x5f, 0x76, 0xaf, 0xca, 0xd9, 0x4c, 0xb1, 0xde, 0x3c, 0x6d,
	0x38, 0xd8, 0xfa, 0xac, 0x32, 0x91, 0x2a, 0xc6, 0x2e, 0xd4, 0x13, 0xb5, 0x3e, 0xf2, 0x79, 0x79,
	0x3b, 0x83, 0x6e, 0x39, 0x79, 0xc1, 0x32, 0x7f, 0x32, 0xde, 0x43, 0xdb, 0x68, 0x0f, 0x69, 0xb8,
	0xa0, 0x3d, 0xe3, 0x60, 0x54, 0x1c, 0xc2, 0xe8, 0xf4, 0xa7, 0x07, 0x9d, 0x4f, 0x6f, 0x92, 0x64,
	0xfa, 0xb0, 0x2a, 0x4e, 0xe6, 0xee, 0x23, 0x00, 0x00, 0xff, 0xff, 0x84, 0xe0, 0x82, 0x73, 0x46,
	0x02, 0x00, 0x00,
}
