// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ManagerSession struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	RoleID               uint64   `protobuf:"varint,4,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerSession) Reset()         { *m = ManagerSession{} }
func (m *ManagerSession) String() string { return proto.CompactTextString(m) }
func (*ManagerSession) ProtoMessage()    {}
func (*ManagerSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_731bccb2b1d8e983, []int{0}
}
func (m *ManagerSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerSession.Unmarshal(m, b)
}
func (m *ManagerSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerSession.Marshal(b, m, deterministic)
}
func (dst *ManagerSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerSession.Merge(dst, src)
}
func (m *ManagerSession) XXX_Size() int {
	return xxx_messageInfo_ManagerSession.Size(m)
}
func (m *ManagerSession) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerSession.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerSession proto.InternalMessageInfo

func (m *ManagerSession) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ManagerSession) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ManagerSession) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ManagerSession) GetRoleID() uint64 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *ManagerSession) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*ManagerSession)(nil), "protos.ManagerSession")
}

func init() { proto.RegisterFile("session", fileDescriptor_session_731bccb2b1d8e983) }

var fileDescriptor_session_731bccb2b1d8e983 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x2f, 0x4e, 0x2d, 0x2e,
	0xce, 0xcc, 0xcf, 0x13, 0x62, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0x56, 0x6a, 0x62, 0xe4, 0xe2,
	0xf3, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0x0a, 0x86, 0x4a, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x31, 0x79, 0xba, 0x08, 0x09, 0x71, 0xb1, 0xf8, 0x25, 0xe6,
	0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x0a, 0x5c, 0xdc, 0x2e, 0x99,
	0xc5, 0x05, 0x39, 0x89, 0x95, 0x60, 0x29, 0x66, 0xb0, 0x14, 0xb2, 0x90, 0x90, 0x18, 0x17, 0x5b,
	0x50, 0x7e, 0x4e, 0xaa, 0xa7, 0x8b, 0x04, 0x0b, 0xd8, 0x24, 0x28, 0x0f, 0x64, 0x1a, 0x88, 0x25,
	0xc1, 0x0a, 0x31, 0x0d, 0xc4, 0x4e, 0x82, 0x38, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x61,
	0x8a, 0xcc, 0x83, 0x9e, 0x00, 0x00, 0x00,
}
