// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trashcan

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTrashCanDeviceGroupsRequest struct {
	Pagination           *Pagination `protobuf:"bytes,1,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	CustomerID           uint64      `protobuf:"varint,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTrashCanDeviceGroupsRequest) Reset()         { *m = GetTrashCanDeviceGroupsRequest{} }
func (m *GetTrashCanDeviceGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTrashCanDeviceGroupsRequest) ProtoMessage()    {}
func (*GetTrashCanDeviceGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_trashcan_1e4abfc3d69e3012, []int{0}
}
func (m *GetTrashCanDeviceGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrashCanDeviceGroupsRequest.Unmarshal(m, b)
}
func (m *GetTrashCanDeviceGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrashCanDeviceGroupsRequest.Marshal(b, m, deterministic)
}
func (dst *GetTrashCanDeviceGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrashCanDeviceGroupsRequest.Merge(dst, src)
}
func (m *GetTrashCanDeviceGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTrashCanDeviceGroupsRequest.Size(m)
}
func (m *GetTrashCanDeviceGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrashCanDeviceGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrashCanDeviceGroupsRequest proto.InternalMessageInfo

func (m *GetTrashCanDeviceGroupsRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetTrashCanDeviceGroupsRequest) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *GetTrashCanDeviceGroupsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TrashCanDeviceGroup struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CustomerID           uint64   `protobuf:"varint,3,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	DeviceTotal          uint64   `protobuf:"varint,4,opt,name=DeviceTotal,proto3" json:"DeviceTotal,omitempty"`
	DeviceOn             uint64   `protobuf:"varint,5,opt,name=DeviceOn,proto3" json:"DeviceOn,omitempty"`
	DeviceOff            uint64   `protobuf:"varint,6,opt,name=DeviceOff,proto3" json:"DeviceOff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrashCanDeviceGroup) Reset()         { *m = TrashCanDeviceGroup{} }
func (m *TrashCanDeviceGroup) String() string { return proto.CompactTextString(m) }
func (*TrashCanDeviceGroup) ProtoMessage()    {}
func (*TrashCanDeviceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_trashcan_1e4abfc3d69e3012, []int{1}
}
func (m *TrashCanDeviceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrashCanDeviceGroup.Unmarshal(m, b)
}
func (m *TrashCanDeviceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrashCanDeviceGroup.Marshal(b, m, deterministic)
}
func (dst *TrashCanDeviceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrashCanDeviceGroup.Merge(dst, src)
}
func (m *TrashCanDeviceGroup) XXX_Size() int {
	return xxx_messageInfo_TrashCanDeviceGroup.Size(m)
}
func (m *TrashCanDeviceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TrashCanDeviceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TrashCanDeviceGroup proto.InternalMessageInfo

func (m *TrashCanDeviceGroup) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TrashCanDeviceGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrashCanDeviceGroup) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *TrashCanDeviceGroup) GetDeviceTotal() uint64 {
	if m != nil {
		return m.DeviceTotal
	}
	return 0
}

func (m *TrashCanDeviceGroup) GetDeviceOn() uint64 {
	if m != nil {
		return m.DeviceOn
	}
	return 0
}

func (m *TrashCanDeviceGroup) GetDeviceOff() uint64 {
	if m != nil {
		return m.DeviceOff
	}
	return 0
}

type GetTrashCanDeviceGroupsResponse struct {
	List                 []*TrashCanDeviceGroup `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64                 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	CurrentPage          uint64                 `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64                 `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64                 `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetTrashCanDeviceGroupsResponse) Reset()         { *m = GetTrashCanDeviceGroupsResponse{} }
func (m *GetTrashCanDeviceGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTrashCanDeviceGroupsResponse) ProtoMessage()    {}
func (*GetTrashCanDeviceGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_trashcan_1e4abfc3d69e3012, []int{2}
}
func (m *GetTrashCanDeviceGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrashCanDeviceGroupsResponse.Unmarshal(m, b)
}
func (m *GetTrashCanDeviceGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrashCanDeviceGroupsResponse.Marshal(b, m, deterministic)
}
func (dst *GetTrashCanDeviceGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrashCanDeviceGroupsResponse.Merge(dst, src)
}
func (m *GetTrashCanDeviceGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTrashCanDeviceGroupsResponse.Size(m)
}
func (m *GetTrashCanDeviceGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrashCanDeviceGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrashCanDeviceGroupsResponse proto.InternalMessageInfo

func (m *GetTrashCanDeviceGroupsResponse) GetList() []*TrashCanDeviceGroup {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetTrashCanDeviceGroupsResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetTrashCanDeviceGroupsResponse) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *GetTrashCanDeviceGroupsResponse) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetTrashCanDeviceGroupsResponse) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

// 与普通Device结构相比, TrashcanDevice多了一个占用率字段
type TrashcanDevice struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	SerialNumber         string   `protobuf:"bytes,3,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Position             string   `protobuf:"bytes,5,opt,name=Position,proto3" json:"Position,omitempty"`
	Group                string   `protobuf:"bytes,11,opt,name=Group,proto3" json:"Group,omitempty"`
	GroupID              uint64   `protobuf:"varint,12,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	DeviceType           string   `protobuf:"bytes,13,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	DeviceTypeID         uint64   `protobuf:"varint,14,opt,name=DeviceTypeID,proto3" json:"DeviceTypeID,omitempty"`
	DeviceModel          string   `protobuf:"bytes,15,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
	DeviceModelID        uint64   `protobuf:"varint,16,opt,name=DeviceModelID,proto3" json:"DeviceModelID,omitempty"`
	Customer             string   `protobuf:"bytes,17,opt,name=Customer,proto3" json:"Customer,omitempty"`
	CustomerID           uint64   `protobuf:"varint,18,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Latitude             float64  `protobuf:"fixed64,21,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,22,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	StatusCode           uint64   `protobuf:"varint,23,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Status               string   `protobuf:"bytes,24,opt,name=Status,proto3" json:"Status,omitempty"`
	Percent              float64  `protobuf:"fixed64,30,opt,name=Percent,proto3" json:"Percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrashcanDevice) Reset()         { *m = TrashcanDevice{} }
func (m *TrashcanDevice) String() string { return proto.CompactTextString(m) }
func (*TrashcanDevice) ProtoMessage()    {}
func (*TrashcanDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_trashcan_1e4abfc3d69e3012, []int{3}
}
func (m *TrashcanDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrashcanDevice.Unmarshal(m, b)
}
func (m *TrashcanDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrashcanDevice.Marshal(b, m, deterministic)
}
func (dst *TrashcanDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrashcanDevice.Merge(dst, src)
}
func (m *TrashcanDevice) XXX_Size() int {
	return xxx_messageInfo_TrashcanDevice.Size(m)
}
func (m *TrashcanDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_TrashcanDevice.DiscardUnknown(m)
}

var xxx_messageInfo_TrashcanDevice proto.InternalMessageInfo

func (m *TrashcanDevice) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TrashcanDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrashcanDevice) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *TrashcanDevice) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TrashcanDevice) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *TrashcanDevice) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *TrashcanDevice) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *TrashcanDevice) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *TrashcanDevice) GetDeviceTypeID() uint64 {
	if m != nil {
		return m.DeviceTypeID
	}
	return 0
}

func (m *TrashcanDevice) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *TrashcanDevice) GetDeviceModelID() uint64 {
	if m != nil {
		return m.DeviceModelID
	}
	return 0
}

func (m *TrashcanDevice) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *TrashcanDevice) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *TrashcanDevice) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *TrashcanDevice) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *TrashcanDevice) GetStatusCode() uint64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *TrashcanDevice) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TrashcanDevice) GetPercent() float64 {
	if m != nil {
		return m.Percent
	}
	return 0
}

type TrashcanDeviceList struct {
	List                 []*TrashcanDevice `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64            `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	CurrentPage          uint64            `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64            `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64            `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TrashcanDeviceList) Reset()         { *m = TrashcanDeviceList{} }
func (m *TrashcanDeviceList) String() string { return proto.CompactTextString(m) }
func (*TrashcanDeviceList) ProtoMessage()    {}
func (*TrashcanDeviceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_trashcan_1e4abfc3d69e3012, []int{4}
}
func (m *TrashcanDeviceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrashcanDeviceList.Unmarshal(m, b)
}
func (m *TrashcanDeviceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrashcanDeviceList.Marshal(b, m, deterministic)
}
func (dst *TrashcanDeviceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrashcanDeviceList.Merge(dst, src)
}
func (m *TrashcanDeviceList) XXX_Size() int {
	return xxx_messageInfo_TrashcanDeviceList.Size(m)
}
func (m *TrashcanDeviceList) XXX_DiscardUnknown() {
	xxx_messageInfo_TrashcanDeviceList.DiscardUnknown(m)
}

var xxx_messageInfo_TrashcanDeviceList proto.InternalMessageInfo

func (m *TrashcanDeviceList) GetList() []*TrashcanDevice {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *TrashcanDeviceList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TrashcanDeviceList) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *TrashcanDeviceList) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *TrashcanDeviceList) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type TrashcanAlarmThreshold struct {
	StageInfo            float64  `protobuf:"fixed64,1,opt,name=StageInfo,proto3" json:"StageInfo,omitempty"`
	StageWarn            float64  `protobuf:"fixed64,2,opt,name=StageWarn,proto3" json:"StageWarn,omitempty"`
	StageAlert           float64  `protobuf:"fixed64,3,opt,name=StageAlert,proto3" json:"StageAlert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrashcanAlarmThreshold) Reset()         { *m = TrashcanAlarmThreshold{} }
func (m *TrashcanAlarmThreshold) String() string { return proto.CompactTextString(m) }
func (*TrashcanAlarmThreshold) ProtoMessage()    {}
func (*TrashcanAlarmThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_trashcan_1e4abfc3d69e3012, []int{5}
}
func (m *TrashcanAlarmThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrashcanAlarmThreshold.Unmarshal(m, b)
}
func (m *TrashcanAlarmThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrashcanAlarmThreshold.Marshal(b, m, deterministic)
}
func (dst *TrashcanAlarmThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrashcanAlarmThreshold.Merge(dst, src)
}
func (m *TrashcanAlarmThreshold) XXX_Size() int {
	return xxx_messageInfo_TrashcanAlarmThreshold.Size(m)
}
func (m *TrashcanAlarmThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_TrashcanAlarmThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_TrashcanAlarmThreshold proto.InternalMessageInfo

func (m *TrashcanAlarmThreshold) GetStageInfo() float64 {
	if m != nil {
		return m.StageInfo
	}
	return 0
}

func (m *TrashcanAlarmThreshold) GetStageWarn() float64 {
	if m != nil {
		return m.StageWarn
	}
	return 0
}

func (m *TrashcanAlarmThreshold) GetStageAlert() float64 {
	if m != nil {
		return m.StageAlert
	}
	return 0
}

type TrashcanDeviceWithAlarmThreshold struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Position             string   `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position,omitempty"`
	SerialNumber         string   `protobuf:"bytes,4,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	GroupID              uint64   `protobuf:"varint,5,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Group                string   `protobuf:"bytes,6,opt,name=Group,proto3" json:"Group,omitempty"`
	DeviceModelID        uint64   `protobuf:"varint,7,opt,name=DeviceModelID,proto3" json:"DeviceModelID,omitempty"`
	DeviceModel          string   `protobuf:"bytes,8,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
	CreatedAt            string   `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	StageInfo            float64  `protobuf:"fixed64,20,opt,name=StageInfo,proto3" json:"StageInfo,omitempty"`
	StageWarn            float64  `protobuf:"fixed64,21,opt,name=StageWarn,proto3" json:"StageWarn,omitempty"`
	StageAlert           float64  `protobuf:"fixed64,22,opt,name=StageAlert,proto3" json:"StageAlert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrashcanDeviceWithAlarmThreshold) Reset()         { *m = TrashcanDeviceWithAlarmThreshold{} }
func (m *TrashcanDeviceWithAlarmThreshold) String() string { return proto.CompactTextString(m) }
func (*TrashcanDeviceWithAlarmThreshold) ProtoMessage()    {}
func (*TrashcanDeviceWithAlarmThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_trashcan_1e4abfc3d69e3012, []int{6}
}
func (m *TrashcanDeviceWithAlarmThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrashcanDeviceWithAlarmThreshold.Unmarshal(m, b)
}
func (m *TrashcanDeviceWithAlarmThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrashcanDeviceWithAlarmThreshold.Marshal(b, m, deterministic)
}
func (dst *TrashcanDeviceWithAlarmThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrashcanDeviceWithAlarmThreshold.Merge(dst, src)
}
func (m *TrashcanDeviceWithAlarmThreshold) XXX_Size() int {
	return xxx_messageInfo_TrashcanDeviceWithAlarmThreshold.Size(m)
}
func (m *TrashcanDeviceWithAlarmThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_TrashcanDeviceWithAlarmThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_TrashcanDeviceWithAlarmThreshold proto.InternalMessageInfo

func (m *TrashcanDeviceWithAlarmThreshold) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TrashcanDeviceWithAlarmThreshold) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrashcanDeviceWithAlarmThreshold) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *TrashcanDeviceWithAlarmThreshold) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *TrashcanDeviceWithAlarmThreshold) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *TrashcanDeviceWithAlarmThreshold) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *TrashcanDeviceWithAlarmThreshold) GetDeviceModelID() uint64 {
	if m != nil {
		return m.DeviceModelID
	}
	return 0
}

func (m *TrashcanDeviceWithAlarmThreshold) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *TrashcanDeviceWithAlarmThreshold) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *TrashcanDeviceWithAlarmThreshold) GetStageInfo() float64 {
	if m != nil {
		return m.StageInfo
	}
	return 0
}

func (m *TrashcanDeviceWithAlarmThreshold) GetStageWarn() float64 {
	if m != nil {
		return m.StageWarn
	}
	return 0
}

func (m *TrashcanDeviceWithAlarmThreshold) GetStageAlert() float64 {
	if m != nil {
		return m.StageAlert
	}
	return 0
}

type TrashcanAlarmThresholdList struct {
	Count                uint64                              `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	List                 []*TrashcanDeviceWithAlarmThreshold `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	CurrentPage          uint64                              `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64                              `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64                              `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *TrashcanAlarmThresholdList) Reset()         { *m = TrashcanAlarmThresholdList{} }
func (m *TrashcanAlarmThresholdList) String() string { return proto.CompactTextString(m) }
func (*TrashcanAlarmThresholdList) ProtoMessage()    {}
func (*TrashcanAlarmThresholdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_trashcan_1e4abfc3d69e3012, []int{7}
}
func (m *TrashcanAlarmThresholdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrashcanAlarmThresholdList.Unmarshal(m, b)
}
func (m *TrashcanAlarmThresholdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrashcanAlarmThresholdList.Marshal(b, m, deterministic)
}
func (dst *TrashcanAlarmThresholdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrashcanAlarmThresholdList.Merge(dst, src)
}
func (m *TrashcanAlarmThresholdList) XXX_Size() int {
	return xxx_messageInfo_TrashcanAlarmThresholdList.Size(m)
}
func (m *TrashcanAlarmThresholdList) XXX_DiscardUnknown() {
	xxx_messageInfo_TrashcanAlarmThresholdList.DiscardUnknown(m)
}

var xxx_messageInfo_TrashcanAlarmThresholdList proto.InternalMessageInfo

func (m *TrashcanAlarmThresholdList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TrashcanAlarmThresholdList) GetList() []*TrashcanDeviceWithAlarmThreshold {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *TrashcanAlarmThresholdList) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *TrashcanAlarmThresholdList) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *TrashcanAlarmThresholdList) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GetTrashCanDeviceGroupsRequest)(nil), "protos.GetTrashCanDeviceGroupsRequest")
	proto.RegisterType((*TrashCanDeviceGroup)(nil), "protos.TrashCanDeviceGroup")
	proto.RegisterType((*GetTrashCanDeviceGroupsResponse)(nil), "protos.GetTrashCanDeviceGroupsResponse")
	proto.RegisterType((*TrashcanDevice)(nil), "protos.TrashcanDevice")
	proto.RegisterType((*TrashcanDeviceList)(nil), "protos.TrashcanDeviceList")
	proto.RegisterType((*TrashcanAlarmThreshold)(nil), "protos.TrashcanAlarmThreshold")
	proto.RegisterType((*TrashcanDeviceWithAlarmThreshold)(nil), "protos.TrashcanDeviceWithAlarmThreshold")
	proto.RegisterType((*TrashcanAlarmThresholdList)(nil), "protos.TrashcanAlarmThresholdList")
}

func init() { proto.RegisterFile("trashcan", fileDescriptor_trashcan_1e4abfc3d69e3012) }

var fileDescriptor_trashcan_1e4abfc3d69e3012 = []byte{
	// 692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xd5, 0x24, 0x4e, 0x9a, 0xdc, 0xb4, 0xfd, 0x3e, 0x86, 0x36, 0x8c, 0x42, 0x55, 0x2c, 0x8b,
	0x45, 0xc4, 0xa2, 0x48, 0x65, 0xcb, 0xa6, 0x4a, 0xa4, 0x2a, 0x52, 0x29, 0x95, 0x13, 0xa9, 0xeb,
	0x69, 0x32, 0x4d, 0x2c, 0x25, 0x9e, 0x30, 0x1e, 0x23, 0xc1, 0x13, 0xf0, 0x0c, 0x3c, 0x07, 0xbc,
	0x02, 0x4b, 0x9e, 0x87, 0x25, 0x9a, 0x3b, 0xfe, 0x19, 0x27, 0xa1, 0xea, 0x06, 0xb1, 0x8a, 0xcf,
	0xb9, 0x33, 0xd7, 0xf7, 0x1e, 0x9f, 0xa3, 0x40, 0x4b, 0x2b, 0x9e, 0x2c, 0xa6, 0x3c, 0xa6, 0xcd,
	0xb5, 0x92, 0x5a, 0x26, 0xbd, 0xe6, 0x54, 0xae, 0x56, 0x32, 0x0e, 0xbe, 0x10, 0x38, 0xbd, 0x14,
	0x7a, 0x62, 0xea, 0x03, 0x1e, 0x0f, 0xc5, 0xc7, 0x68, 0x2a, 0x2e, 0x95, 0x4c, 0xd7, 0x49, 0x28,
	0x3e, 0xa4, 0x22, 0xd1, 0xf4, 0x1c, 0xe0, 0x86, 0xcf, 0xa3, 0x98, 0xeb, 0x48, 0xc6, 0x8c, 0xf8,
	0xa4, 0xdf, 0x39, 0xa7, 0x67, 0xb6, 0xcf, 0x59, 0x59, 0x09, 0x9d, 0x53, 0xf4, 0x14, 0x60, 0x90,
	0x26, 0x5a, 0xae, 0x84, 0x1a, 0x0d, 0x59, 0xcd, 0x27, 0x7d, 0x2f, 0x74, 0x18, 0x4a, 0xc1, 0xbb,
	0xe6, 0x2b, 0xc1, 0xea, 0x3e, 0xe9, 0xb7, 0x43, 0x7c, 0x0e, 0xbe, 0x13, 0x78, 0xba, 0x63, 0x0e,
	0x7a, 0x08, 0xb5, 0xd1, 0x10, 0xdf, 0xeb, 0x85, 0x35, 0xe7, 0x6e, 0xad, 0xbc, 0xbb, 0xf1, 0xbe,
	0xfa, 0xd6, 0xfb, 0x7c, 0xe8, 0xd8, 0x96, 0x13, 0xa9, 0xf9, 0x92, 0x79, 0x78, 0xc0, 0xa5, 0x68,
	0x0f, 0x5a, 0x16, 0xbe, 0x8f, 0x59, 0x03, 0xcb, 0x05, 0xa6, 0x27, 0xd0, 0xce, 0x9e, 0xef, 0xef,
	0x59, 0x13, 0x8b, 0x25, 0x11, 0xfc, 0x20, 0xf0, 0xe2, 0x8f, 0x12, 0x26, 0x6b, 0x19, 0x27, 0x82,
	0xbe, 0x06, 0xef, 0x2a, 0x4a, 0x34, 0x23, 0x7e, 0xbd, 0xdf, 0x39, 0x7f, 0x9e, 0xab, 0xb7, 0xe3,
	0x4e, 0x88, 0x07, 0xe9, 0x11, 0x34, 0x06, 0x32, 0x8d, 0x75, 0xa6, 0x9d, 0x05, 0x66, 0x8d, 0x41,
	0xaa, 0x94, 0x88, 0xf5, 0x0d, 0x9f, 0x0b, 0x06, 0x76, 0x0d, 0x87, 0x32, 0x6b, 0x98, 0xdf, 0x71,
	0xf4, 0x59, 0xb0, 0x8e, 0x5d, 0x23, 0xc7, 0x46, 0x24, 0xdc, 0xd5, 0x36, 0xde, 0xb7, 0x22, 0x95,
	0x4c, 0xf0, 0xd5, 0x83, 0xc3, 0x49, 0x66, 0x14, 0x3b, 0xd1, 0xa3, 0xb4, 0x0f, 0x60, 0x7f, 0x2c,
	0x54, 0xc4, 0x97, 0xd7, 0xe9, 0xea, 0x4e, 0xa8, 0xec, 0x9b, 0x56, 0x38, 0xab, 0x7f, 0x32, 0x55,
	0xd1, 0x1a, 0x4d, 0xe4, 0xe1, 0x11, 0x97, 0xc2, 0xc1, 0x65, 0x12, 0x61, 0xb9, 0x81, 0xe5, 0x02,
	0x1b, 0x31, 0x50, 0x1b, 0xdc, 0xa8, 0x1d, 0x5a, 0x40, 0x19, 0xec, 0xe1, 0xc3, 0x68, 0x98, 0xed,
	0x92, 0x43, 0xb3, 0x68, 0xf6, 0x69, 0x3f, 0xad, 0x05, 0x3b, 0xc0, 0x4b, 0x0e, 0x63, 0x26, 0x2e,
	0xd1, 0x68, 0xc8, 0x0e, 0xf1, 0x7a, 0x85, 0x2b, 0x1d, 0xf3, 0x4e, 0xce, 0xc4, 0x92, 0xfd, 0x97,
	0x4f, 0x5c, 0x50, 0xf4, 0x25, 0x1c, 0x38, 0x70, 0x34, 0x64, 0xff, 0x63, 0x9b, 0x2a, 0x69, 0xf6,
	0xca, 0x7d, 0xc8, 0x9e, 0xd8, 0xbd, 0x72, 0xbc, 0xe1, 0x5a, 0xba, 0xe5, 0xda, 0x1e, 0xb4, 0xae,
	0xb8, 0x8e, 0x74, 0x3a, 0x13, 0xec, 0xd8, 0x27, 0x7d, 0x12, 0x16, 0xd8, 0x78, 0xf2, 0x4a, 0xc6,
	0x73, 0x5b, 0xec, 0x62, 0xb1, 0x24, 0x4c, 0xe7, 0xb1, 0xe6, 0x3a, 0x4d, 0x06, 0x72, 0x26, 0xd8,
	0x33, 0xdb, 0xb9, 0x64, 0x68, 0x17, 0x9a, 0x16, 0x31, 0x86, 0x33, 0x65, 0xc8, 0x68, 0x7a, 0x23,
	0xd4, 0x54, 0xc4, 0x9a, 0x9d, 0x62, 0xcf, 0x1c, 0x06, 0xdf, 0x08, 0xd0, 0xaa, 0x39, 0xd0, 0xa7,
	0xaf, 0x2a, 0xc6, 0xee, 0x56, 0x8c, 0x5d, 0x9c, 0xfc, 0x87, 0x9e, 0xd6, 0xd0, 0xcd, 0x67, 0xb9,
	0x58, 0x72, 0xb5, 0x9a, 0x2c, 0x94, 0x48, 0x16, 0x72, 0x39, 0x33, 0x02, 0x8e, 0x35, 0x9f, 0x8b,
	0x51, 0x7c, 0x2f, 0xd1, 0xe1, 0x24, 0x2c, 0x89, 0xa2, 0x7a, 0xcb, 0x55, 0x8c, 0xf3, 0xe6, 0x55,
	0x43, 0x64, 0xf2, 0xce, 0xc5, 0xc5, 0x52, 0x28, 0x8d, 0x86, 0x27, 0xa1, 0xc3, 0x04, 0xbf, 0x6a,
	0xe0, 0x57, 0x25, 0xb8, 0x8d, 0xf4, 0x62, 0x63, 0x80, 0xc7, 0x64, 0xcb, 0x4d, 0x45, 0x7d, 0x23,
	0x15, 0x9b, 0xb9, 0xf3, 0x76, 0xe4, 0xce, 0xc9, 0x48, 0xa3, 0x9a, 0x91, 0x22, 0x53, 0x4d, 0x37,
	0x53, 0x5b, 0x9e, 0xde, 0xdb, 0xe5, 0xe9, 0x8d, 0x6c, 0xb4, 0xb6, 0xb3, 0x71, 0x02, 0xed, 0x81,
	0x12, 0x5c, 0x8b, 0xd9, 0x85, 0xce, 0x52, 0x5b, 0x12, 0x55, 0xe9, 0x8f, 0x1e, 0x94, 0xfe, 0xf8,
	0x61, 0xe9, 0xbb, 0x5b, 0xd2, 0xff, 0x24, 0xd0, 0xdb, 0xfd, 0xc5, 0xab, 0x1e, 0x24, 0xae, 0x07,
	0xdf, 0x66, 0x2e, 0xae, 0xa1, 0x8b, 0xfb, 0xbb, 0x5d, 0xbc, 0xfd, 0x09, 0x33, 0x5f, 0xff, 0x55,
	0x07, 0xdf, 0xd9, 0x7f, 0xec, 0x37, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xef, 0x9d, 0xcb, 0xa0,
	0xc4, 0x07, 0x00, 0x00,
}
