// Code generated by protoc-gen-go. DO NOT EDIT.
// source: water_level

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WaterLevelAlarmThreshold struct {
	LowStageWarn         float64  `protobuf:"fixed64,1,opt,name=LowStageWarn,proto3" json:"LowStageWarn,omitempty"`
	LowStageInfo         float64  `protobuf:"fixed64,2,opt,name=LowStageInfo,proto3" json:"LowStageInfo,omitempty"`
	HighStageInfo        float64  `protobuf:"fixed64,3,opt,name=HighStageInfo,proto3" json:"HighStageInfo,omitempty"`
	HighStageWarn        float64  `protobuf:"fixed64,4,opt,name=HighStageWarn,proto3" json:"HighStageWarn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaterLevelAlarmThreshold) Reset()         { *m = WaterLevelAlarmThreshold{} }
func (m *WaterLevelAlarmThreshold) String() string { return proto.CompactTextString(m) }
func (*WaterLevelAlarmThreshold) ProtoMessage()    {}
func (*WaterLevelAlarmThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_water_level_17320bb7469da7a0, []int{0}
}
func (m *WaterLevelAlarmThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterLevelAlarmThreshold.Unmarshal(m, b)
}
func (m *WaterLevelAlarmThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterLevelAlarmThreshold.Marshal(b, m, deterministic)
}
func (dst *WaterLevelAlarmThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterLevelAlarmThreshold.Merge(dst, src)
}
func (m *WaterLevelAlarmThreshold) XXX_Size() int {
	return xxx_messageInfo_WaterLevelAlarmThreshold.Size(m)
}
func (m *WaterLevelAlarmThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterLevelAlarmThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_WaterLevelAlarmThreshold proto.InternalMessageInfo

func (m *WaterLevelAlarmThreshold) GetLowStageWarn() float64 {
	if m != nil {
		return m.LowStageWarn
	}
	return 0
}

func (m *WaterLevelAlarmThreshold) GetLowStageInfo() float64 {
	if m != nil {
		return m.LowStageInfo
	}
	return 0
}

func (m *WaterLevelAlarmThreshold) GetHighStageInfo() float64 {
	if m != nil {
		return m.HighStageInfo
	}
	return 0
}

func (m *WaterLevelAlarmThreshold) GetHighStageWarn() float64 {
	if m != nil {
		return m.HighStageWarn
	}
	return 0
}

type WaterLevelDevice struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	SerialNumber         string   `protobuf:"bytes,3,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Position             string   `protobuf:"bytes,5,opt,name=Position,proto3" json:"Position,omitempty"`
	Group                string   `protobuf:"bytes,11,opt,name=Group,proto3" json:"Group,omitempty"`
	GroupID              uint64   `protobuf:"varint,12,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	DeviceType           string   `protobuf:"bytes,13,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	DeviceTypeID         uint64   `protobuf:"varint,14,opt,name=DeviceTypeID,proto3" json:"DeviceTypeID,omitempty"`
	DeviceModel          string   `protobuf:"bytes,15,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
	DeviceModelID        uint64   `protobuf:"varint,16,opt,name=DeviceModelID,proto3" json:"DeviceModelID,omitempty"`
	Customer             string   `protobuf:"bytes,17,opt,name=Customer,proto3" json:"Customer,omitempty"`
	CustomerID           uint64   `protobuf:"varint,18,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Latitude             float64  `protobuf:"fixed64,21,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,22,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	StatusCode           uint64   `protobuf:"varint,31,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Status               string   `protobuf:"bytes,32,opt,name=Status,proto3" json:"Status,omitempty"`
	MID                  uint64   `protobuf:"varint,33,opt,name=MID,proto3" json:"MID,omitempty"`
	UplinkAt             string   `protobuf:"bytes,34,opt,name=UplinkAt,proto3" json:"UplinkAt,omitempty"`
	NID                  uint64   `protobuf:"varint,35,opt,name=NID,proto3" json:"NID,omitempty"`
	AlertAt              string   `protobuf:"bytes,36,opt,name=AlertAt,proto3" json:"AlertAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaterLevelDevice) Reset()         { *m = WaterLevelDevice{} }
func (m *WaterLevelDevice) String() string { return proto.CompactTextString(m) }
func (*WaterLevelDevice) ProtoMessage()    {}
func (*WaterLevelDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_water_level_17320bb7469da7a0, []int{1}
}
func (m *WaterLevelDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterLevelDevice.Unmarshal(m, b)
}
func (m *WaterLevelDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterLevelDevice.Marshal(b, m, deterministic)
}
func (dst *WaterLevelDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterLevelDevice.Merge(dst, src)
}
func (m *WaterLevelDevice) XXX_Size() int {
	return xxx_messageInfo_WaterLevelDevice.Size(m)
}
func (m *WaterLevelDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterLevelDevice.DiscardUnknown(m)
}

var xxx_messageInfo_WaterLevelDevice proto.InternalMessageInfo

func (m *WaterLevelDevice) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *WaterLevelDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WaterLevelDevice) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *WaterLevelDevice) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *WaterLevelDevice) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *WaterLevelDevice) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *WaterLevelDevice) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *WaterLevelDevice) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *WaterLevelDevice) GetDeviceTypeID() uint64 {
	if m != nil {
		return m.DeviceTypeID
	}
	return 0
}

func (m *WaterLevelDevice) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *WaterLevelDevice) GetDeviceModelID() uint64 {
	if m != nil {
		return m.DeviceModelID
	}
	return 0
}

func (m *WaterLevelDevice) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *WaterLevelDevice) GetCustomerID() uint64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *WaterLevelDevice) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *WaterLevelDevice) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *WaterLevelDevice) GetStatusCode() uint64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *WaterLevelDevice) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *WaterLevelDevice) GetMID() uint64 {
	if m != nil {
		return m.MID
	}
	return 0
}

func (m *WaterLevelDevice) GetUplinkAt() string {
	if m != nil {
		return m.UplinkAt
	}
	return ""
}

func (m *WaterLevelDevice) GetNID() uint64 {
	if m != nil {
		return m.NID
	}
	return 0
}

func (m *WaterLevelDevice) GetAlertAt() string {
	if m != nil {
		return m.AlertAt
	}
	return ""
}

type WaterLevelDeviceList struct {
	List                 []*WaterLevelDevice `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Count                uint64              `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	CurrentPage          uint64              `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64              `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64              `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WaterLevelDeviceList) Reset()         { *m = WaterLevelDeviceList{} }
func (m *WaterLevelDeviceList) String() string { return proto.CompactTextString(m) }
func (*WaterLevelDeviceList) ProtoMessage()    {}
func (*WaterLevelDeviceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_water_level_17320bb7469da7a0, []int{2}
}
func (m *WaterLevelDeviceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterLevelDeviceList.Unmarshal(m, b)
}
func (m *WaterLevelDeviceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterLevelDeviceList.Marshal(b, m, deterministic)
}
func (dst *WaterLevelDeviceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterLevelDeviceList.Merge(dst, src)
}
func (m *WaterLevelDeviceList) XXX_Size() int {
	return xxx_messageInfo_WaterLevelDeviceList.Size(m)
}
func (m *WaterLevelDeviceList) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterLevelDeviceList.DiscardUnknown(m)
}

var xxx_messageInfo_WaterLevelDeviceList proto.InternalMessageInfo

func (m *WaterLevelDeviceList) GetList() []*WaterLevelDevice {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *WaterLevelDeviceList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *WaterLevelDeviceList) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *WaterLevelDeviceList) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *WaterLevelDeviceList) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type WaterLevelDeviceWithAlarmThreshold struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Position             string   `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position,omitempty"`
	SerialNumber         string   `protobuf:"bytes,4,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	GroupID              uint64   `protobuf:"varint,5,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Group                string   `protobuf:"bytes,6,opt,name=Group,proto3" json:"Group,omitempty"`
	DeviceModelID        uint64   `protobuf:"varint,7,opt,name=DeviceModelID,proto3" json:"DeviceModelID,omitempty"`
	DeviceModel          string   `protobuf:"bytes,8,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
	CreatedAt            string   `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	LowStageWarn         float64  `protobuf:"fixed64,20,opt,name=LowStageWarn,proto3" json:"LowStageWarn,omitempty"`
	LowStageInfo         float64  `protobuf:"fixed64,21,opt,name=LowStageInfo,proto3" json:"LowStageInfo,omitempty"`
	HighStageInfo        float64  `protobuf:"fixed64,22,opt,name=HighStageInfo,proto3" json:"HighStageInfo,omitempty"`
	HighStageWarn        float64  `protobuf:"fixed64,23,opt,name=HighStageWarn,proto3" json:"HighStageWarn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaterLevelDeviceWithAlarmThreshold) Reset()         { *m = WaterLevelDeviceWithAlarmThreshold{} }
func (m *WaterLevelDeviceWithAlarmThreshold) String() string { return proto.CompactTextString(m) }
func (*WaterLevelDeviceWithAlarmThreshold) ProtoMessage()    {}
func (*WaterLevelDeviceWithAlarmThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_water_level_17320bb7469da7a0, []int{3}
}
func (m *WaterLevelDeviceWithAlarmThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterLevelDeviceWithAlarmThreshold.Unmarshal(m, b)
}
func (m *WaterLevelDeviceWithAlarmThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterLevelDeviceWithAlarmThreshold.Marshal(b, m, deterministic)
}
func (dst *WaterLevelDeviceWithAlarmThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterLevelDeviceWithAlarmThreshold.Merge(dst, src)
}
func (m *WaterLevelDeviceWithAlarmThreshold) XXX_Size() int {
	return xxx_messageInfo_WaterLevelDeviceWithAlarmThreshold.Size(m)
}
func (m *WaterLevelDeviceWithAlarmThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterLevelDeviceWithAlarmThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_WaterLevelDeviceWithAlarmThreshold proto.InternalMessageInfo

func (m *WaterLevelDeviceWithAlarmThreshold) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetGroupID() uint64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetDeviceModelID() uint64 {
	if m != nil {
		return m.DeviceModelID
	}
	return 0
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetLowStageWarn() float64 {
	if m != nil {
		return m.LowStageWarn
	}
	return 0
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetLowStageInfo() float64 {
	if m != nil {
		return m.LowStageInfo
	}
	return 0
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetHighStageInfo() float64 {
	if m != nil {
		return m.HighStageInfo
	}
	return 0
}

func (m *WaterLevelDeviceWithAlarmThreshold) GetHighStageWarn() float64 {
	if m != nil {
		return m.HighStageWarn
	}
	return 0
}

type WaterLevelAlarmThresholdList struct {
	Count                uint64                                `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	List                 []*WaterLevelDeviceWithAlarmThreshold `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	CurrentPage          uint64                                `protobuf:"varint,10,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	PageSize             uint64                                `protobuf:"varint,11,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalCount           uint64                                `protobuf:"varint,12,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *WaterLevelAlarmThresholdList) Reset()         { *m = WaterLevelAlarmThresholdList{} }
func (m *WaterLevelAlarmThresholdList) String() string { return proto.CompactTextString(m) }
func (*WaterLevelAlarmThresholdList) ProtoMessage()    {}
func (*WaterLevelAlarmThresholdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_water_level_17320bb7469da7a0, []int{4}
}
func (m *WaterLevelAlarmThresholdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterLevelAlarmThresholdList.Unmarshal(m, b)
}
func (m *WaterLevelAlarmThresholdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterLevelAlarmThresholdList.Marshal(b, m, deterministic)
}
func (dst *WaterLevelAlarmThresholdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterLevelAlarmThresholdList.Merge(dst, src)
}
func (m *WaterLevelAlarmThresholdList) XXX_Size() int {
	return xxx_messageInfo_WaterLevelAlarmThresholdList.Size(m)
}
func (m *WaterLevelAlarmThresholdList) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterLevelAlarmThresholdList.DiscardUnknown(m)
}

var xxx_messageInfo_WaterLevelAlarmThresholdList proto.InternalMessageInfo

func (m *WaterLevelAlarmThresholdList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *WaterLevelAlarmThresholdList) GetList() []*WaterLevelDeviceWithAlarmThreshold {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *WaterLevelAlarmThresholdList) GetCurrentPage() uint64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *WaterLevelAlarmThresholdList) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *WaterLevelAlarmThresholdList) GetTotalCount() uint64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*WaterLevelAlarmThreshold)(nil), "protos.WaterLevelAlarmThreshold")
	proto.RegisterType((*WaterLevelDevice)(nil), "protos.WaterLevelDevice")
	proto.RegisterType((*WaterLevelDeviceList)(nil), "protos.WaterLevelDeviceList")
	proto.RegisterType((*WaterLevelDeviceWithAlarmThreshold)(nil), "protos.WaterLevelDeviceWithAlarmThreshold")
	proto.RegisterType((*WaterLevelAlarmThresholdList)(nil), "protos.WaterLevelAlarmThresholdList")
}

func init() { proto.RegisterFile("water_level", fileDescriptor_water_level_17320bb7469da7a0) }

var fileDescriptor_water_level_17320bb7469da7a0 = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0xda, 0xec, 0x47, 0xdd, 0x6d, 0x14, 0xab, 0x2b, 0x16, 0xaa, 0xa0, 0x84, 0x1d, 0x26,
	0x84, 0x76, 0x80, 0x3b, 0x52, 0xd5, 0x48, 0x10, 0xa9, 0xab, 0xa6, 0xb4, 0xa8, 0x47, 0xe4, 0xad,
	0x8f, 0x36, 0x22, 0x8d, 0x2b, 0xc7, 0xd9, 0x04, 0x7f, 0x14, 0x07, 0x4e, 0xfc, 0x1d, 0x9c, 0xf9,
	0x63, 0x90, 0x9f, 0x9b, 0xc6, 0x49, 0x3b, 0xa9, 0x17, 0x4e, 0xf5, 0xf7, 0xbd, 0xcf, 0xee, 0x97,
	0xf8, 0x7b, 0x2f, 0xa4, 0xf9, 0xc0, 0x15, 0xc8, 0x2f, 0x31, 0xdc, 0x43, 0x4c, 0x0f, 0x57, 0x52,
	0x28, 0x91, 0x7a, 0x3f, 0x1d, 0xc2, 0xa6, 0x9a, 0x1f, 0x6a, 0xba, 0x1f, 0x73, 0xb9, 0x9c, 0x2c,
	0x24, 0xa4, 0x0b, 0x11, 0xcf, 0xa8, 0x47, 0x4e, 0x86, 0xe2, 0x61, 0xac, 0xf8, 0x1c, 0xa6, 0x5c,
	0x26, 0xcc, 0xe9, 0x39, 0x97, 0x4e, 0x58, 0xe2, 0x6c, 0x4d, 0x90, 0x7c, 0x15, 0xac, 0x56, 0xd6,
	0x68, 0x8e, 0x5e, 0x90, 0xd3, 0x4f, 0xd1, 0x7c, 0x51, 0x88, 0xea, 0x28, 0x2a, 0x93, 0x25, 0x15,
	0xfe, 0x9d, 0x5b, 0x51, 0x69, 0xd2, 0xfb, 0xeb, 0x92, 0x56, 0x61, 0xd8, 0x87, 0xfb, 0xe8, 0x0e,
	0xe8, 0x19, 0xa9, 0x05, 0x3e, 0xda, 0x73, 0xc3, 0x5a, 0xe0, 0x53, 0x4a, 0xdc, 0x11, 0x5f, 0x02,
	0x9a, 0x69, 0x84, 0xb8, 0xd6, 0x46, 0xc7, 0x20, 0x23, 0x1e, 0x8f, 0xb2, 0xe5, 0x2d, 0x48, 0xf4,
	0xd0, 0x08, 0x4b, 0x1c, 0xed, 0x91, 0xa6, 0x0f, 0xe9, 0x9d, 0x8c, 0x56, 0x2a, 0x12, 0xc6, 0x40,
	0x23, 0xb4, 0x29, 0xfa, 0x9c, 0x1c, 0xdf, 0x88, 0x34, 0xc2, 0xf2, 0x01, 0x96, 0x37, 0x98, 0xb6,
	0xc9, 0xc1, 0x47, 0x29, 0xb2, 0x15, 0x6b, 0x62, 0xc1, 0x00, 0xca, 0xc8, 0x11, 0x2e, 0x02, 0x9f,
	0x9d, 0xa0, 0xc1, 0x1c, 0xd2, 0x17, 0x84, 0x18, 0xff, 0x93, 0xef, 0x2b, 0x60, 0xa7, 0xb8, 0xc9,
	0x62, 0xb4, 0xe3, 0x02, 0x05, 0x3e, 0x3b, 0xc3, 0xed, 0x25, 0xce, 0x38, 0xd6, 0xf8, 0x5a, 0xcc,
	0x20, 0x66, 0x4f, 0x72, 0xc7, 0x1b, 0x4a, 0xbf, 0x56, 0x0b, 0x06, 0x3e, 0x6b, 0xe1, 0x31, 0x65,
	0x52, 0x3f, 0xd7, 0x20, 0x4b, 0x95, 0x58, 0x82, 0x64, 0x4f, 0xcd, 0x73, 0xe5, 0x58, 0xfb, 0xcc,
	0xd7, 0x81, 0xcf, 0x28, 0x6e, 0xb7, 0x18, 0xbd, 0x77, 0xc8, 0x55, 0xa4, 0xb2, 0x19, 0xb0, 0x73,
	0xbc, 0xb3, 0x0d, 0xa6, 0x5d, 0xd2, 0x18, 0x8a, 0x64, 0x6e, 0x8a, 0x1d, 0x2c, 0x16, 0x84, 0x3e,
	0x79, 0xac, 0xb8, 0xca, 0xd2, 0x81, 0x98, 0x01, 0x7b, 0x69, 0x4e, 0x2e, 0x18, 0xda, 0x21, 0x87,
	0x06, 0xb1, 0x1e, 0x7a, 0x5a, 0x23, 0xda, 0x22, 0xf5, 0xeb, 0xc0, 0x67, 0xaf, 0x70, 0x83, 0x5e,
	0x6a, 0x0f, 0x9f, 0x57, 0x71, 0x94, 0x7c, 0xeb, 0x2b, 0xe6, 0x19, 0xff, 0x39, 0xd6, 0xea, 0x51,
	0xe0, 0xb3, 0xd7, 0x46, 0x3d, 0x0a, 0x7c, 0x7d, 0x27, 0xfd, 0x18, 0xa4, 0xea, 0x2b, 0x76, 0x81,
	0xe2, 0x1c, 0x7a, 0xbf, 0x1d, 0xd2, 0xae, 0xc6, 0x6b, 0x18, 0xa5, 0x8a, 0xbe, 0x25, 0xae, 0xfe,
	0x65, 0x4e, 0xaf, 0x7e, 0xd9, 0x7c, 0xc7, 0xae, 0x4c, 0xff, 0x5c, 0x55, 0xb5, 0x21, 0xaa, 0x74,
	0x14, 0x06, 0x22, 0x4b, 0x14, 0x26, 0xd0, 0x0d, 0x0d, 0xd0, 0x97, 0x35, 0xc8, 0xa4, 0x84, 0x44,
	0xdd, 0xf0, 0x39, 0x30, 0x82, 0x35, 0x9b, 0xc2, 0x78, 0xf1, 0x39, 0x8c, 0xa3, 0x1f, 0x80, 0x29,
	0x72, 0xc3, 0x0d, 0xd6, 0x2f, 0x6b, 0x22, 0x14, 0x8f, 0xcd, 0xc1, 0x26, 0x4b, 0x16, 0xe3, 0xfd,
	0xaa, 0x13, 0xaf, 0x6a, 0x67, 0x1a, 0xa9, 0x45, 0xa5, 0xa9, 0xf7, 0xe9, 0x15, 0x3b, 0xe5, 0xf5,
	0x4a, 0xca, 0xab, 0x7d, 0xe4, 0xee, 0xe8, 0x23, 0x2b, 0xf3, 0x07, 0xe5, 0xcc, 0x6f, 0x7a, 0xe4,
	0xd0, 0xee, 0x91, 0xad, 0x8c, 0x1e, 0xed, 0xca, 0x68, 0x25, 0xeb, 0xc7, 0xdb, 0x59, 0xef, 0x92,
	0xc6, 0x40, 0x02, 0x57, 0x30, 0xeb, 0xab, 0x75, 0x17, 0x16, 0xc4, 0xd6, 0x38, 0x6b, 0xef, 0x31,
	0xce, 0xce, 0xf7, 0x19, 0x67, 0x9d, 0xbd, 0xc6, 0xd9, 0xb3, 0x5d, 0xe3, 0xec, 0x8f, 0x43, 0xba,
	0x8f, 0xcd, 0xdf, 0x72, 0x92, 0x1c, 0x3b, 0x49, 0x1f, 0xd6, 0x69, 0xac, 0x61, 0x1a, 0xdf, 0x3c,
	0x96, 0xc6, 0xed, 0xeb, 0x5f, 0xe7, 0xf3, 0xbf, 0x26, 0xf1, 0xd6, 0x7c, 0x5c, 0xde, 0xff, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x7c, 0x83, 0x91, 0xc2, 0x72, 0x06, 0x00, 0x00,
}
